### ISSUE TITLE
Process jpg images as progressive by default

### ISSUE THREAD

**Issue by hhoechtl** [neos/neos-development-collection#1175]
If you use images on your website (no matter if thumbnails or full size images) you usually want the images to be progressive.
The used Imagine library supports interlacing of images: \Imagine\Image\ImageInterface::interlace.
It would be cool, if that setting could be made globally e.g.

```
TYPO3:
  Media:
    image:
      defaultOptions:
        interlace: 'plane'
        'quality': 90
        convertCMYKToRGB: true
```
