### ISSUE TITLE
Adjust the fusion autoIncude path 

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-development-collection#1344]
Atm fusion checks for configured autoIncludes at 
```
Neos:
  Neos:
    typoScript:
      autoInclude:
```

but should be 

```
Neos:
  Neos:
    fusion:
      autoInclude:
```
