### ISSUE TITLE
Workspace Review module not showing document nodes created in different dimensions

### ISSUE THREAD

**Issue by franklinkim** [neos/neos-development-collection#1458]
### Description

As discussed with @kdambekalns:
If you create a document node in one dimension and edit it in another, the workspace review module only shows the initial node but not the one in the other dimension. 

Notes:
Unpublished content elements of these two nodes are being showed.
If you just publish the document node in the one dimension it shows it will show the unpublished dimension afterwards.

### Steps to Reproduce

Dimension Config:

```yaml
TYPO3:
  TYPO3CR:
    contentDimensions:
      language:
        default: en
        defaultPreset: en
        icon: icon-language
        label: Language
        presets:
          en:
            label: English
            uriSegment: en
            values:
              - en
          de:
            label: German
            uriSegment: de
            values:
              - de
              - en
      country:
        default: all
        defaultPreset: all
        label: Country
        icon: icon-globe
        presets:
          all:
            label: International
            values:
              - all
            uriSegment: all
          de:
            label: Germany
            values:
              - de
              - all
            uriSegment: de

```

Workspace setup: Shared Workspace "review" based on "live"

1. Create Page *test* in dimension `language: en, country: all`
2. Switch dimension to  `language: en, country: de`
3. Edit the Title
4. Publish all to `review` Workspace

#### Expected behavior

Show unpublished changes for *test* page in the dimensions

* `language: en, country: all`
* `language: en, country: de`

#### Actual behavior

Only shows unpublished changes for *test* page in the dimensions

* `language: en, country: all`

### Affected Versions

Neos: 2.3.10

Flow: 3.3.8
