### ISSUE TITLE
Custom Validators for inspector: path to validator needs additional ../../

### ISSUE THREAD

**Issue by coders-market** [neos/neos-development-collection#1562]
### Path to FooValidator.js can't be resolved
If you add a custom validator for the inspector, the path to the FooValidator.js is wrong and therefore be loaded.

### Steps to Reproduce

1. Add to your `Settings.yaml` the `requireJsPathMapping`:

```
Neos:
  Neos:
    userInterface:
      requireJsPathMapping:
        '<My.Package.Name>/Validation': 'resource://<My.Package.Name>/Public/JavaScript/Inspector/Validators'
```

2. Add your custom validator to a NodeType property:
```
  properties:
    foo:
      type: string
      validation:
        '<My.Package.Name>/JavaScript/Inspector/Validators/FooValidator': []
``` 

3. Got to your Neos backend to the nodetype which is using this validator and have a look into your browser console. 

#### Expected behavior

No error, path to FooValidator.js is resolved correctly to: 
`http://127.0.0.1:8081/_Resources/Static/Packages/<My.Package>/Inspector/Validators/FooValidator.js`

#### Actual behavior

Wrong path to FooValidator.js:
`http://127.0.0.1:8081/_Resources/Static/Packages/Neos.Neos/JavaScript/<My.Package>/Inspector/Validators/FooValidator.js`

### Current Workaround
Add `../../` to your validation:
```
  properties:
    foo:
      type: string
      validation:
        '../../<My.Package.Name>/JavaScript/Inspector/Validators/FooValidator': []
``` 

### Affected Versions

Neos:  2.3.12, 3.0.3, 3.1.0
