### ISSUE TITLE
Same uri segment for different dimensions is not possible

### ISSUE THREAD

**Issue by mgoldbeck** [neos/neos-development-collection#1642]
### Description

I have two dimensions with one preset for “de” each and which should be default. So the default uri part should be “de_de”. But if I change the language to English the backend ist still rendered in the de_de context, also shown in the data-neos-context-dimensions=“{”language”:[“de”],“market”:[“de”]}, but the uri is correct. As an example http://neos31.dev/fr_de@user-admin;language=fr&market=de

### Steps to Reproduce

1. used Settings in neos development distribution
```
contentDimensions:
  language:
    label: language
    icon: icon-language
    default: de
    defaultPreset: de
    presets:
      all: null
      de:
        label: German
        values:
          - de
        uriSegment: de
      en_US:
        label: English
        values:
          - en_US
          - de
        uriSegment: en
  market:
    label: market
    icon: icon-globe
    default: de
    defaultPreset: de
    presets:
      de:
        label: Germany
        values:
          - de
        uriSegment: de
      at:
        label: Austria
        values:
          - at
        uriSegment: at
      ch:
        label: Switzerland
        values:
          - ch
        uriSegment: ch
```
#### Expected behavior

The dimensions are changeable in the Backend and the right combinations is shown and used

#### Actual behavior

It is not possible to change to another language dimension

### Affected Versions

Neos: 3.1 old and new ui
