### ISSUE TITLE
No recursive includes in Settings.yaml

### ISSUE THREAD

**Issue by putzwasser** [neos/neos-development-collection#1683]
### Description

Neos doesn't import translation files recursively.

### Steps to Reproduce
1. Create dummy NodeType
```
'V.S:DirA.DirB.TestNodeType':
  superTypes:
    'Neos.Neos:Document': true
  ui:
    label: 'i18n'
  properties:
    test:
      type: 'string'
      ui:
        label: 'i18n'
        inspector:
          group: 'document'
```
2. Create a XLIFF file in V.S/Resources/Private/Translations/en/NodeTypes/DirA/DirB/TestNodeType.xlf
```
<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
	<file original="" product-name="V.S" source-language="en" datatype="plaintext">
		<body>
			<!-- UI strings -->
			<trans-unit id="ui.label" xml:space="preserve">
				<source>Test</source>
			</trans-unit>
			<!-- property strings -->
			<trans-unit id="properties.test" xml:space="preserve">
				<source>Pleaser enter a String</source>
			</trans-unit>
			<!-- /property strings -->
		</body>
	</file>
</xliff>
```
3. Add the following to your `Settings.yaml`
```
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'V.S': ['NodeTypes/**/*', 'NodeTypes/*']
```
4. Create the node

#### Expected behavior

Correctly "translated"/named NodeType/Property

#### Actual behavior

Identifier `V.S:DirA.DirB.TestNodeType:properties.test` as output instead of a translated string.

### Affected Versions

Neos: 3.1.5

Flow: 4.1.6
