### ISSUE TITLE
Property title can't contain dash

### ISSUE THREAD

**Issue by hhoechtl** [neos/neos-development-collection#1717]
### Description

When naming a property with a dash e.g. `background-position` with a `SelectBoxEditor` the Neos backend doesn't recognize a change when switching values in the select box and therefore you can't store it. 
It's even not stored when changing another property.

### Steps to Reproduce

Create a Node with this definition:
```yaml
'Some.Test:Test':
  superTypes:
    'Neos.Neos:Content': true
  ui:
    label: 'TEST'
  properties:
    'background-position':
      type: string
      defaultValue: 'foo'
      ui:
        label: 'Background position'
        reloadIfChanged: true
        inspector:
          group: 'type'
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            values:
              'some':
                label: 'Some'
              'other':
                label: 'Other'
              'foo':
                label: 'Foo'
```

Then place the content element somewhere and try to change the value of the property `background-position` in the inspector. The apply button remains unchanged and you can't persist the value.

#### Expected behavior

Properties should either work with every name including special chars or Neos should throw an error or notice informing that the property name is not stable.

As the new React UI seems unaffected, it might be just to fix the old UI.

#### Actual behavior

The property is displayed but it doesn't work and you keep digging for errors.

### Affected Versions

Neos: 3.2  classic UI

The new React UI is not affected.
