### ISSUE TITLE
NodeTree presets

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#1952]
With the current version it is already possible to filter nodes in the `NodeTree` based on their type using the [Node tree base node type](http://neos.readthedocs.io/en/stable/References/Configuration/Configuration.html#node-tree-base-node-type) settings.

As the documentation states, this has been prepared already to be extensible so that different presets can be pre-configured.

I'm not perfectly sure how this could be implemented UX-wise, but maybe just with a special section in the filter something like:
![image](https://user-images.githubusercontent.com/307571/37032122-a983b152-2141-11e8-820a-799bd134d72a.png)

The corresponding settings could look like

```yaml
Neos:
  Neos:
    userInterface:
      navigateComponent:
        nodeTree:
          presets:
            'default':
              baseNodeType: 'Neos.Neos:Document'
            'my-custom':
              ui:
                label: 'Custom Preset'
                icon: 'icon-foo'
              baseNodeType: 'Neos.Neos:Document,!My.Special:NodeType'
```
