### ISSUE TITLE
CreateNodePrivilege only works partially

### ISSUE THREAD

**Issue by ComiR** [neos/neos-development-collection#1978]
### Description
I had a `Policy.yaml` similiar to this:
```yaml
privilegeTargets:
  Neos\Neos\Security\Authorization\Privilege\NodeTreePrivilege:
    'Some.Package:SubpageTree':
      matcher: >-
        nodeIsOfType("Neos.Neos:Document")
        && !nodeIsOfType("Some.Package:Homepage")
  Neos\ContentRepository\Security\Authorization\Privilege\Node\CreateNodePrivilege:
    'Some.Package:NodeCreation':
      matcher: nodeIsOfType("Some.Package:Homepage")
```
These privileges should abstain for the user in question.
Using `neos/neos-ui`, the option to create a node into the 'Some.Package:Homepage' wasn't present, but using `host.tld/neos/legacy` it was. So I tried creating it and ran into the problem that the node was created, but I wasn't allowed to set any properties (i.e. the `uriPathSegment`), which resulted in other problems (see neos/neos-ui#1718 for those).
I should not have been able to create the node in the first place. So that is the problem I'm reporting here.
Using a matcher `createdNodeIsOfType("Some.Package:OtherPage")` seems to work though.

### Steps to Reproduce
1. In `Policy.yaml` put sth like
```yaml
privilegeTargets:
  Neos\ContentRepository\Security\Authorization\Privilege\Node\CreateNodePrivilege:
    'Some.Package:NodeCreation':
      matcher: nodeIsOfType("Some.Package:NodeType")
roles:
  'Neos.Neos:AbstractEditor':
    privileges:
      -
        privilegeTarget: 'Some.Package:NodeCreation'
        permission: DENY
```
2. Create a node of type `Some.Package:NodeType`
3. Create a subnode of any type

#### Expected behavior
Node creation denied because of privilege denying creation of nodes in regard to `Some.Package:NodeType`.

#### Actual behavior
Node created successfully.

### Affected Versions
Neos: 3.3.9
Flow: 4.3.4
