### ISSUE TITLE
Uri always contain the default dimensions preset

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-development-collection#2059]
### Description

If you configure to allow empty uriSegments for the default dimension preset. You will get the problem that the generated URL will always contain the uriSegment. Even if you want to ignore that.

http://neos.readthedocs.io/en/3.3/CreatingASite/ContentDimensions.html

Configuration is like:

```
ContentRepository:
    contentDimensions:
      'language':
        label: 'Language'
        icon: 'icon-language'
        default: 'de'
        defaultPreset: 'de'
        presets:
          'de':
            label: 'Deutsch'
            values: ['de']
            uriSegment: 'de'
```

supportEmptySegmentForDimensions is true in the backend and the URLs without the segment can be resolved.

### Steps to Reproduce

1. Configure your dimensions to allow empty segment
2. clear all caches
3. Render the page

#### Expected behavior

The generated URLs does not contain the uriSegment ... in my case "de"

#### Actual behavior

The generated URLs  contain the uriSegment ... in my case "de" and you can call the URLs without the segment.

### Affected Versions

Neos: 3.3

Flow: 4.x
