### ISSUE TITLE
Inline editable interferes with cursor in Chrome

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#2076]
### Description

When using two inline editable properties for non-block elements, the RTE seems to mess with the cursor leading to the sensation of typing backwards:

![neos_rte_bug](https://user-images.githubusercontent.com/307571/40913279-645b9f50-67f4-11e8-8206-1f99118b6f83.gif)

### Steps to Reproduce

1. Create a NodeType with two inline editable properties

Example definition:
```yaml
'Neos.Demo:Test':
  superTypes:
    'Neos.Neos:Content': true
  ui:
    label: 'TEST'
    inlineEditable: true
  properties:
    'property1':
      type: string
      defaultValue: ''
      ui:
        inlineEditable: true
        aloha:
          placeholder: 'Some placeholder'
    'property2':
      type: string
      defaultValue: ''
      ui:
        inlineEditable: true
        aloha:
          placeholder: 'Some other placeholder'
```
Example template:
```html
{namespace neos=Neos\Neos\ViewHelpers}
<div>
	<h2>{neos:contentElement.editable(property: 'property1', tag: 'span')}</h2>
	<p>{neos:contentElement.editable(property: 'property2', tag: 'span')}</p>
</div>
```
2. Insert a node of that type, select the first placeholder and start to type

#### Expected behavior

The first placeholder should disappear and the first property can be edited

#### Actual behavior

The second editable property is selected. While typing the cursor jumps randomly(?) making it impossible to correctly edit the value.

### Affected Versions

Neos: 4.0 (but probably all with the new UI/RTE)
