### ISSUE TITLE
Setup tool does not support environment variables

### ISSUE THREAD

**Issue by rolandschuetz** [neos/neos-development-collection#2346]
### Description
Let's say a Configuration/Settings.yaml with the following exists:
```
Neos:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: '%env:NEOS_DATABASE_NAME%'
        user: '%env:NEOS_DATABASE_USER%'
        password: '%env:NEOS_DATABASE_PASS%'
        host: '%env:NEOS_DATABASE_HOST%'
        port: '%env:NEOS_DATABASE_PORT%'
```

The setup tool will not be able to handle it:
1) It shows validation errors e.g. in the database port field.
2) When trying to connect to the database it does not resolve the environment variables.

### Steps to Reproduce

1. Configure a Settings.yaml as shown above
2. Open the setup tool and go to the step, where the database is configured.

#### Expected behavior

It should allow environment variables in form fields, and resolve them when connecting to the database.

#### Actual behavior

See above.

### Affected Versions

Neos: *
