### ISSUE TITLE
References properties with dynamic startingPoint

### ISSUE THREAD

**Issue by pduersteler** [neos/neos-development-collection#2353]
### Description

Properties of type `references` have an editor option `startingPoint`. From the docs at https://neos.readthedocs.io/en/stable/References/PropertyEditorReference.html#property-type-reference-references-referenceeditor-referenceseditor-reference-selection-editors:

> The starting point (node path) for finding possible nodes to create a reference. This allows to search for nodes outside the current site. If not given, nodes will be searched for in the current site.

Said editor option does only support a simple string, but not an eel expression. Allowing eel expressions would allow a more dynamic selection, e.g. when creating a form finisher that needs to reference input field nodes from the current form (as nodes from other forms would not make any sense).

### Steps to Reproduce

1. Set up a property of type `references` in a node type
2. Configure `startingPoint` inside `editorOptions` with an eel expression

#### Expected behavior

The reference property editor scopes the given search words to the node from the eel expression.

#### Actual behavior

An error occurs due to the expression not being supported.

### Affected Versions

Neos:  4.2.4
Flow: 5.2.2

**Comment by bwaidelich** [comment]
Thanks for creating the issue!
I'd like to have a more flexible reference lookup, but I'm really skeptical when it comes to mixing languages into configuration.
We already do that for Node labels, but IMO that should have been a `LabelGenerator` with corresponding options.

My concerns:
* Very poor IDE support¹
* Therefore prone to errors (that might only occur at runtime and in certain conditions)
* It's not clear where Eel expressions are supported
* In some cases (not in this one) it might not be clear whether the given value should be a literal or an Eel expression
* The Eel Parser needs a context - it is not clear what that context is

What about something like:

```yaml
editorOptions:
  startingPointResolver: 'Some\Resolver\ClassName'
  startingPointOptions:
    foo: 'bar'
```

The class could be required to implement some `NodeResolverInterface` or similar - and there could be some `EelExpressionNodeResolver` class that expects some expression as option. But personally I would try to avoid it, at least for more complex lookups.

----
¹ in Neos.Neos we have
```yaml
'Neos.Neos:Node':
  label: "${String.cropAtWord(String.trim(String.stripTags(String.pregReplace(q(node).property('title') || q(node).property('text') || ((I18n.translate(node.nodeType.label) || node.nodeType.name) + (node.autoCreated ? ' (' + node.name + ')' : '')), '/<br\\W*?\\/?>|\\x{00a0}|[[^:print:]]|\\s+/u', ' '))), 100, '...')}"
  abstract: true
  // ...
```
o.O

**Comment by bwaidelich** [comment]
```yaml
editorOptions:
  startingPoint:
    resolver: 'Some\Resolver\ClassName'
    resolverOptions:
      foo: 'bar'
```
might be nicer
