### ISSUE TITLE
Publishing slow depending on workspace amount caused by inefficient cache clearing

### ISSUE THREAD

**Issue by mwitte** [neos/neos-development-collection#2424]
### Description

I've got a problem on neos 4.2 with publishing. I think this problem exists since 4.1(caching changes)

Publishing is very very slow. The more workspaces exist and the more content is in the Neos_Fusion_Content cache it slows heavily down. I've found out the problem is the tagging. If i changen only one node(Something simple like a Text node), this change will clear the cache by tag

[workspace part]
- Node_(workspacehash)_7cd42355-da78-4e53-baf6-48001f6c7f74 (node identifier)
- DescendantOf_(workspacehash)_7cd42355-da78-4e53-baf6-48001f6c7f74 (node identifier)
- NodeType_(workspacehash)_Neos.NodeTypes:Text
- NodeType_(workspacehash)_Neos.Neos:Content
- NodeType_(workspacehash)_Neos.Neos:Node
- NodeType_(workspacehash)_Neos.Neos:Node
- NodeType_(workspacehash)_Neos.Neos:Hidable
- ... (all other supertypes and mixins)

[/workspace part]
- Node_7cd42355-da78-4e53-baf6-48001f6c7f74 (node identifier)
- DescendantOf_7cd42355-da78-4e53-baf6-48001f6c7f74 (node identifier)
- NodeType_Neos.NodeTypes:Text
- NodeType_Neos.Neos:Content
- NodeType_Neos.Neos:Node
- NodeType_Neos.Neos:Node
- NodeType_Neos.Neos:Hidable
- ... (all other supertypes and mixins)

So far so good. All this seems correctly. But after this, it iterates over all workspaces and repeats the [workspace part] for each workspace.

In my special case(~25 Workspaces) this means the Neos\Neos\Fusion\Cache\ContentCacheFlusher adds more than 400 entry into it's class property "tagsToFlush" which results in more than 400 calls of the Neos\Cache\Backend\<TaggableBackendInterface>->flushByTag() method for one single change of a Textnode.

I've replaces the default CacheBackend but I think one single change for publishing should not result trying to clear cache entries by so many cache entries.

### Steps to Reproduce

1. have a neos instance with multiple workspaces(for example multiple at least one time logged in backend users)
2. fill the Neos_Fusion_Content by crawling the page 
3. do a change in the backend and try to publish
4. recognize that the publishing is very very slow if there are lots of workspaces and the Neos_Fusion_Content is filled(for example by crawling the frontend) 

#### Expected behavior

Fast publishing for the target workspace, clearing caches for the target workspace

#### Actual behavior

Slow publishing caused of trying to clear caches for each workspace wich slows down publishing

### Affected Versions
Currently I'm on 4.2.9 but I think problem exists since 4.1 but didn't test it

**Comment by Kleisli** [comment]
I guess, I encounter the same problem in a Neos 7.0 installation with 12 BE users (= 12 workspaces). After some time, publishing is getting painfully slow, but when I clear the cache, it's ok again. I didn't dig deep into the problem, but it sounds like it could be the same problem.

@mwitte Did you find a solution to deal with this problem?

**Comment by DrillSergeant** [comment]
@Kleisli Till, do you use Redis? If not, this may be an issue with that. Almost every Neos instance of us is slow when it grows a little if we dont configure redis caches like this:
```
Neos_Fusion_Content:
  backend: Neos\Cache\Backend\RedisBackend
  backendOptions:
    hostname: ddev-neosdraft-redis
    port: 6379
    defaultLifetime: 0
    database: 10
Flow_Mvc_Routing_Resolve:
  backend: Neos\Cache\Backend\RedisBackend
  backendOptions:
    hostname: ddev-neosdraft-redis
    port: 6379
    defaultLifetime: 0
    database: 10
Flow_Mvc_Routing_Route:
  backend: Neos\Cache\Backend\RedisBackend
  backendOptions:
    hostname: ddev-neosdraft-redis
    port: 6379
    defaultLifetime: 0
    database: 10
Flow_Session_MetaData:
  backend: Neos\Cache\Backend\RedisBackend
  backendOptions:
    hostname: ddev-neosdraft-redis
    port: 6379
    defaultLifetime: 0
    database: 10
Flow_Session_Storage:
  backend: Neos\Cache\Backend\RedisBackend
  backendOptions:
    hostname: ddev-neosdraft-redis
    port: 6379
    defaultLifetime: 0
    database: 10


```
