### ISSUE TITLE
NodeType inheritance is not working correct

### ISSUE THREAD

**Issue by breadlesscode** [neos/neos-development-collection#2663]
### Description

I inherit from a abstract Nodetype. And the boolean property always have to redefined. 

### Steps to Reproduce

1. Create a mixin (see below)
2. Inherit from that mixin
3. Override `ui.inspector.group` property
4. Have a look at the inspector. You should see `Missing editor definition`. 

You can fix that by redefining the property type.. 

Abstract/Mixin:
```
'Demo.Demo:Mixin.TextColor':
  abstract: true
  properties:
    isTextColorInverted:
      type: boolean
      defaultValue: false
      ui:
        label: i18n
        reloadIfChanged: true
```
NodeType
```
'Demo.Demo:Content.TextBox':
  superTypes:
    'Neos.Neos:Content': true
    'Demo.Demo:Mixin.TextColor': true
  ui:
    label: i18n
    icon: 'fas fa-paragraph'
    inspector:
      groups:
        options:
          label: i18n
          icon: 'icon-sliders'
  properties:
    isTextColorInverted:
      ui:
        inspector:
          group: 'options'
```
#### Expected behavior

A checkbox appears in Neos Inspector

#### Actual behavior

Neos inspector show `Missing editor definition`

### Affected Versions

Neos: 4.3.3

Flow: 5.3.2
