### ISSUE TITLE
Inaccessible Submodule tiles are not hidden

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#2854]
### Description

When a role has access to some sub module, all sub modules of the given main module are shown in the module overview.
**Note:** Access to the other sub modules is still prohibited, so this is merely a _cosmetic_ bug

### Steps to Reproduce

1. Create Neos user with `Editor` roll
2. Grant the `Editor` role access to some admin modules via `Policy.yaml`:
```yaml
roles:
  'Neos.Neos:Editor':
    privileges:
      -
        privilegeTarget: 'Neos.Neos:Backend.Module.Administration'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos:Backend.Module.Administration.Sites'
        permission: GRANT
```
3. Login with the Editor user and navigate to `/neos/administration`

#### Expected behavior

Only the granted sub module should be visible

[What you expected to happen]
![image](https://user-images.githubusercontent.com/307571/71811250-7aa20700-3074-11ea-85ef-aeeca2598182.png)

#### Actual behavior

All Administration sub modules are visible (and lead to an 403 exception when accessed):

[What actually happened]
![image](https://user-images.githubusercontent.com/307571/71811263-855c9c00-3074-11ea-92a6-f5590e9626cd.png)

### Affected Versions

Neos: 4.3
