### ISSUE TITLE
Sorting of NodeTypePostprocessor

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#2868]
### Description

Using the `postprocessors` configuration, processors can be registered for Node Types.
The order of the applied post processors is currently fixed to the order they appear in the YAML configuration.
But this is not flexible and transparent, especially when using superTypes.

We should allow a `position` to be specified in order to get a deterministic ordering:

```yaml
'Some.Custom:NodeType':
  # ...
  postprocessors:
    SomeCustomTypePostprocessor:
      position: 'end'
      postprocessor: 'Some\TypePostprocessor'
```
