### ISSUE TITLE
CreateNodePrivilege does not respect super types

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#2960]
### Description

When using the `CreateNodePrivilege` in conjunction with the `createdNodeIsOfType` matcher, the corresponding privilege only matches the exact node type.
This is unexpected and error prone, since the other node privileges always respect the super types.

### Steps to Reproduce

1. Create a `CreateNodePrivilege` that targets some super type (for example "Neos.Neos:Document"):
```yaml
privilegeTargets:
  'Neos\ContentRepository\Security\Authorization\Privilege\Node\CreateNodePrivilege':
    'Cornelsen.Webkatalog:Nodes.DisableCreation':
      matcher: 'createdNodeIsOfType("Neos.Neos:Document")'
```
2. Log in to the backend and create a node that implements the specified super type (in this example: any document node)

#### Expected behavior

It should not be possible to create the node (the Neos UI shouldn't even provide that option)

#### Actual behavior

The node can be created
