### ISSUE TITLE
./flow routing:routepath shows wrong route (while correctly routing in frontend)

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#3006]
### Description

```
./flow routing:routepath neos/schema/node-type
Path:
  neos/schema/node-type
Route:
  Name: Neos :: Frontend :: Homepage
  Pattern: {node}
Result:
  Package: Neos.Neos
  Subpackage: -
  Controller: Frontend\Node
  Action: show
  Format: html
Controller:
  Neos\Neos\Controller\Frontend\NodeController
```

Neos: 5.2

Flow: 6.2
