### ISSUE TITLE
Asset manipulation does not get the $property name of the change node property

### ISSUE THREAD

**Issue by Benjamin-K** [neos/neos-development-collection#3253]
### Description

If you want to want to automatically add tags or collections to an uploaded assets, you should be able to update tags or collections as described [here (Tagging Assets automaticalle)](https://docs.neos.io/cms/tutorials/tagging-assets-automatically). 
The problem is, that the AssetManipulator won't get the `$propertyName` the file was uploaded for. `$propertyName` always contains an empty string.

In my case i only had one Asset property which was added through a mixin, so maybe this will work if the property is set directly on the nodetype. Nevertheless the property name should always be set correctly.

### Steps to Reproduce

1. Create a nodetype mixin like this:
    ```yaml
    'Your.Package:Mixin.File':
      abstract: true
      ui:
        creationDialog:
          elements:
            'file':
              ui:
                editorOptions:
                  disabled: false
                  features:
                    upload: true
                    mediaBrowser: false
      properties:
        'file':
          type: Neos\Media\Domain\Model\Asset
          ui:
            label: i18n
            # In my case, the asset can also be added directly in the creation dialog. The manipulation should work in all cases.
            showInCreationDialog: true
            inspector:
              group: default
        'title':
          type: 'string'
          # further code is irrelevant here
    ```
2. Create a nodetype that has the upper mixin as superType:
    ```yaml
    'Your.Package:Atom.File':
      superTypes:
        'Neos.Neos:Content': true
        'Your.Package:Mixin.File': true
      ui:
        label: i18n
        icon: file
    ```
3. Add an AssetManipulator as described in the link above.
4. Somehow log the value of the `$propertyName` and verify that it always contains an empty string.

#### Expected behavior

The `$propertyName` should contain the actual name of the property (`file` in the example above).

#### Actual behavior

The `$propertyName` always contains an empty string.

### Affected Versions

I did not yet check which versions are affected. I will try to add this if i have some time.

Neos: 5.3.1
Flow: 6.3.4
