### ISSUE TITLE
Using the "hideInMenu" toggle for the backend modules breaks the menu

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#3287]
Using the flag
```
    modules:
      management:
        submodules:
          yourModule:
            hideInMenu: true
```
leads to an react error, as `Packages/Application/Neos.Neos.Ui/Resources/Private/Fusion/Backend/Component/ModuleMenu.fusion:52` filters the entry from the module and `Json.stringify(value)` converts that list into an objects instead of a list, as a key is missing.
