### ISSUE TITLE
Add user password policy to settings

### ISSUE THREAD

**Issue by Benjamin-K** [neos/neos-development-collection#3293]
### Description

Hi there,

As security is crucial to many middle to large companies I was searching for something to set up a password policy for Neos for customers that do not manage their logins through LDAP or sth. similar. I found that there are no password requirements in Neos, which is really bad. To improve this, I would suggest adding some basic settings for user passwords to the `Settings.yaml`. 

### Steps to Reproduce

See the following files to see, that there is no check for a valid password:

- [UserCommandController::createCommand](Neos.Neos/Classes/Command/UserCommandController.php#L113) (also setPasswordCommand())
- [UserService::createUser](Neos.Neos/Classes/Domain/Service/UserService.php#L266) (and setUserPassword())
- ...

#### Expected behavior

Password policy could be set through settings, for example:

```yaml
Neos:
  Flow:
    security:
      passwordPolicy:
        minLength: 6
        maxLength: 255
        requireNumbers: false
        requireLetters: false
        requireUppercaseAndLowercase: false
        # for special chars I'd prefer a list of the required special chars, sth. like '$%_-!@'
        requireSpecialChars: ''
```

#### Actual behavior

Password requirements are hardcoded.

### Affected Versions

Neos: All
Flow: All
