### ISSUE TITLE
Media.Browser Views.yaml is incorrect/redundant

### ISSUE THREAD

**Issue by albe** [neos/neos-development-collection#3312]
The current Views.yaml looks like this:
```yaml
-
  requestFilter: 'isFormat("html") && isController("Usage") && isPackage("Neos.Media.Browser")'
  options:
    templatePathAndFilenamePattern: '@templateRoot/@subpackage/Usage/@action.@format'
    partialRootPaths:
      'Neos.Neos': 'resource://Neos.Neos/Private/Partials'
      'Neos.Media.Browser': 'resource://Neos.Media.Browser/Private/Partials'

-
  requestFilter: 'isFormat("html") && isPackage("Neos.Media.Browser")'
  options:
    templatePathAndFilenamePattern: '@templateRoot/@subpackage/Asset/@action.@format'
    partialRootPaths:
      'Neos.Neos': 'resource://Neos.Neos/Private/Partials'
      'Neos.Media.Browser': 'resource://Neos.Media.Browser/Private/Partials'

-
  requestFilter: 'parentRequest.isPackage("Neos.Neos") && isFormat("html") && isPackage("Neos.Media.Browser")'
  options:
    layoutRootPaths:
      'Neos.Media.Browser': 'resource://Neos.Media.Browser/Private/Layouts/Module'
    partialRootPaths:
      'Neos.Neos': 'resource://Neos.Neos/Private/Partials'
      'Neos.Media.Browser': 'resource://Neos.Media.Browser/Private/Partials'
```

However, the last requestFilter has much higher specifity than the others and still matches all requests for Media.Browser package, so only that configuration will ever be used. From the looks, it seems like the expected behaviour was that all matching View configs are merged in specifity order, but in fact only the full config of the highest specifity is used. This means that `templatePathAndFilenamePattern` is never used/overriden. If `parentRequest.isPackage("Neos.Neos")` were added to the other filters, then the `layoutRootPaths` would not be set.
