### ISSUE TITLE
default context can't be resolved for content dimension preset with multiple values

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#3338]
### Description

When defining a content dimension preset with multiple values (fallback) the Neos backend defaults to an invalid context.

### Steps to Reproduce

1. Define at least one content dimension preset with multiple dimension values (e.g. `de`) and make that the default:

```yaml
Neos:
  ContentRepository:
    contentDimensions:
      language:
        default: de
        defaultPreset: de
        presets:
          all:
            values: [all]
            uriSegment: ''
          de:
            values: [de, all]
            uriSegment: 'de'
```

2. Log into the Neos backend

#### Expected behavior

I am redirected to the content module in the configured default context:
`/neos/content?node=<some-node-path>@user-<some-user>;language=de,all`

#### Actual behavior

I am redirected to the content module with a context that doesn't exist:
`/neos/content?node=<some-node-path>@user-<some-user>;language=de`

As a result, nodes from the fallback dimension (`all` in this case) are inaccessible.

### Affected Versions

Neos:  5.3+
