### ISSUE TITLE
Dimensions - Changing structure of translated Content-Nodes causes them to disappear  

### ISSUE THREAD

**Issue by fdsis** [neos/neos-development-collection#3340]
### Description

After moving a `Neos.Demo:Content.Columns.Two` (with translated `Neos.Demo:Content.Text` in its columns) into the column of another `Neos.Demo:Content.Columns.Two` (in the main/fallback-dimension) the  `Neos.Demo:Content.Text`-nodes disappear in the frontend ( in the other dimension).
Tested using the demo-site with minimal changes.

#### Preparation
Changing the constraints of `NodeTypes.Collection.Content.Column.yaml` to enable testing with minimal demo-setup:
```
constraints:
    nodeTypes:
      '*': true
```

Changing the Dimensions in `Settings.yaml` to:
```
contentDimensions:
      language:
        label: 'Language'
        icon: 'icon-language'
        default: de
        defaultPreset: de
        presets:
          de:
            label: 'DE'
            values: [ 'de' ]
            uriSegment: ''
          en:
            label: 'EN'
            values: [ 'en', 'de' ]
            uriSegment: 'en'
```
(and then `./flow node:migrate 20150716212459`, `cache:flush`, etc...)

#### Steps
1. Create new Page called `Test` in language `de`
2. create a `Neos.Demo:Content.Columns.Two` in `main`
2.1. put `Neos.Demo:Content.Text` in `column0` with text `de text 1`
2.2 put `Neos.Demo:Content.Text` in `column1` with text `de text 2`
3. publish all changes to live
4. switch language to 'en'
5. translate texts to `en text 1` and `en text 2`
6. publish all changes to live
7. switch language back to 'de'
8. create a second `Neos.Demo:Content.Columns.Two` in `main`
9. put the first `Neos.Demo:Content.Columns.Two` in `column0` of the second `Neos.Demo:Content.Columns.Two`
10. publish all changes to live
11. open the page in the frontend
12. switching language to 'en'

#### Expected behavior

The page should look like it does in the backend, with all nodes visible.

#### Actual behavior

The two `Neos.Demo:Content.Text` nodes are not rendered. The two `Neos.Demo:Content.Columns.Two` are rendered, though. 

### Affected Versions

Neos: 5.3
