### ISSUE TITLE
BUG: German translation labels missing in Neos.Neos 

### ISSUE THREAD

**Issue by gradinarufelix** [neos/neos-development-collection#3345]
### Description

When switching the default UI language to German, we ran into problems because of missing translation labels. For example, `login.wrongCredentials.title` is missing in the German translation files, which leads to a breaking error. This is because the Translator in Neos.Flow returns `null`, which is not accepted by the `addFlashMessage`method.

### Steps to Reproduce

1. Switch the default UI language

```
Neos:
  Neos:
    userInterface:
      defaultLanguage: de
```

2. Log-in with wrong credentials
3. See the error message

#### Expected behavior

Either the translation should be set, or otherwise a fallback should be rendered.

#### Actual behavior

The fallback is not rendered, instead I get a fatal error: `The message body must be of type string, "NULL" given.`

### Affected Versions

Neos: 7.1

Flow: 7.1

**Comment by albe** [comment]
Thanks for the clear report!

This is a regression from https://github.com/neos/neos-development-collection/pull/3102
See also https://github.com/neos/flow-development-collection/issues/1559#issuecomment-840614514

**Comment by cheindl** [comment]
I ran into the same problem. I temporarily fixed it, by providing a fallback language for Flow:

```
Neos:
  Flow:
    i18n:
      defaultLocale: de
      fallbackRule:
        order: ['en']
```
