### ISSUE TITLE
Override inside NodeTypes folder don't get applied

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-development-collection#3449]
Assume I've the following node type configuration in `NodeTypes.Override.Seo`:

```yaml
'Neos.Seo:TitleTagMixin':
  properties:
    titleOverride:
      validation: ~
```

If I put this file into the `Configuration` folder, the override takes place, if I put it into the new `NodeTypes` folder, the override doesn't gets applied…
