### ISSUE TITLE
Editor default configuration is ignored in creation Dialog elements

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#3471]
### Description

Default configurations for property editors (at `Neos.Neos.userInterface.inspector.dataTypes` and `Neos.Neos.userInterface.inspector.editors`) is not applied for CreationDialog elements.
This means that default editors and `editorOptions` have to be configured explicitly for those currently.

### Steps to Reproduce

1. Create a node type with a creationDialog (without specifying the editor)

```yaml
'Some.Package:SomeNodeType':
  # ...
  ui:
    # ...
    creationDialog:
      elements:
        'someElement':
          type: 'string'
          ui:
            label: 'Some Element'
```

2. Insert a new node of that type in the Neos Backend

#### Expected behavior

The "Some Element" field appears in the Creation Dialog with the default editor (`Neos.Neos/Inspector/Editors/TextFieldEditor`) and all its default options applied.

#### Actual behavior

The field does not appear at all, because the editor is not configured explicitly.

### More advanced example:

Given a node type of

```yaml
'Some.Package:SomeNodeType':
  # ...
  ui:
    # ...
    creationDialog:
      elements:
        'someElement':
          type: 'string'
          ui:
            label: 'Some Element'
            editor: 'Neos.Neos/Inspector/Editors/TextFieldEditor'
```

and `Settings.yaml` with:

```yaml
Neos:
  Neos:
    userInterface:
      inspector:
        dataTypes:
          string:
            defaultValue: 'Default value'
        editors:
          'Neos.Neos/Inspector/Editors/TextFieldEditor':
            editorOptions:
              placeholder: 'Default placeholder'
```

=> Now the field appears in the CreationDialog (since the editor is configured explicitly) but default value and placeholder are not set.

### Affected Versions

Neos: 7+
