### ISSUE TITLE
Rendering a content element in backend mid runtime fails in PHP 8

### ISSUE THREAD

**Issue by MVogge** [neos/neos-development-collection#3514]
### Description

While working on a new NodeType I encountered a php error in the backend. After creating the node in the content tree the element is not rendered at first due to an intended @if condition in the fusion markup. When I set the inspector property that satisfies the @if condition the element should be rendered. Instead the browser console prints:
```
index.js:27 Failed to persist changes Error:
  strrpos(): Argument #3 ($offset) must be contained in argument #1 ($haystack)
  Exception Code	0
  Exception Type	ValueError
  Thrown in File	Packages/Application/Neos.Fusion/Classes/Core/RuntimeConfiguration.php
  Line			72

65.
  strrpos("", "/", -1)
  Packages/Application/Neos.Fusion/Classes/Core/RuntimeConfiguration.php
  00070:         $fusionPathLength = strlen($fusionPath);
  00071:         $offset = $fusionPathLength;
  00072:         while (($offset = strrpos($fusionPath, '/', -($fusionPathLength - $offset + 1))) != false) {
  00073:             $pathPrefix = substr($fusionPath, 0, $offset);
  00074:             if (isset($this->pathCache[$pathPrefix])) {
...
```

After refreshing the website, the Node is displayed correctly and it is possible to change the property without any errors. Somehow the fusionPath is empty when the node changes from not rendered to rendered, which seems to lead to the problem.
A quick workaround for this would be to change line 72 in `RuntimeConfiguration.php` to `while ($fusionPath != "" && ($offset = strrpos($fusionPath...`. With this change the node renders as expected without an error. However I think that the root of the problem lies in the missing fusionPath and this is just a cheap fix.

Furthermore I was able to track the problem down to the combination of Neos 7.2 and PHP 8. The same Neos Version with PHP 7.4 does **not** have this bug.

### Minimal NodeType to reproduce

`NodeTypes.Reproduce.yaml`
```
'Neos.NodeTypes:Reproduce':
  superTypes:
    'Neos.Neos:Content': true
  label: "${q(node).property('label') ? q(node).property('label') : 'Reproduce'}"
  ui:
    label: 'Reproduce'
    inspector:
      groups:
        general:
          label: General
          tab: 'default'
  properties:
    label:
      type: 'string'
      ui:
        label: Label
        reloadIfChanged: true
        inspector:
          group: 'general'
```
`Reproduce.fusion`
```
prototype(Neos.NodeTypes:Reproduce) < prototype(Neos.Neos:ContentComponent) {
    label = ${q(node).property('label')}

    @if.hasLabel = ${q(node).property('label')}

    renderer = afx`
        <p>{props.label}</p>
    `
}
```

### Steps to Reproduce

1. Create a node 'Reproduce' in the Content Tree
2. Change the property 'Label' of the newly create node 
3. Apply the changes 

#### Expected behavior

The node should be rendered in the live preview with the text from the property 'Label'.

#### Actual behavior

An error is thrown and the node is only rendered after a browser refresh.

### Affected Versions

Neos: 7.2.0
Flow: 7.2.1
PHP: 8.0.11

#### Oldest supported version

Neos: 7.2.0
Flow: 7.2.1
PHP: 7.4.24
