### ISSUE TITLE
Bug: Unsetting thumbnail presets leads to exception

### ISSUE THREAD

**Issue by putzwasser** [neos/neos-development-collection#3544]
### Description

If a package creates a thumbnail preset

```
Neos:
  Media:
    thumbnailPresets:
      'V.S:Preset1024':
        format: jpq
        quality: 80
        async: false
        width: 1024
```

and I don't want it in my production environment, I can't unset it:

```
Neos:
  Media:
    thumbnailPresets:
      'V.S:Preset1024': ~
```

### Steps to Reproduce

1. Create a thumbnail preset
2. Set the preset to `null` or `~` (or just create a preset key with null as value)
3. Set `async` thumbnail generation to false
3. Try to upload an image to the Media UI

#### Expected behavior

Upload image, no thumbnail generated

#### Actual behavior

Exception #1447664950 is thrown:

> Thumbnail preset configuration for "V.S:Preset1024" not found.

* in [line 51 of /Production/Cache/Code/Flow_Object_Classes/Neos_Media_Domain_Service_ThumbnailGenerator.php](https://github.com/neos/neos-development-collection/blob/29971ce95314bbcebcafea255a11dc751c86b29a/Neos.Media/Classes/Domain/Service/ThumbnailGenerator.php#L51)

The thumbnail generator service has to skip presets with value == null

#### Why is this important

If I don't set the preset to `null` the thumbnail, which I don't use, gets generated for every image, thus, taking up disk space.
