### ISSUE TITLE
Feature: `./flow package:create` with Root.fusion and `autoInclude` 

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#3787]
### Description

The idea is to make the package creation for Fusion packages simpler.

currently one needs to
- run `./flow package:create Vendor.AdditionalFusionStuff`
- then go to that package, create the `Private/Fusion` folder
- add a `Root.fusion` with `include: ./**/*.fusion`
- create a `Settings.yaml` in Configuration
- add to the settings
```yaml
Neos:
  Neos:
    fusion:
      autoInclude:
        Vendor.AdditionalFusionStuff: true
```

### Proposal

create some kind of kickstart command that will add those files into an existing package or create this package.
