### ISSUE TITLE
BUG: Using ChangePropertyValue node migration with a non-string value doesn't work

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#3801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to set a boolean value, the string replace in the ChangePropertyValue changes that value to a string.

### Expected Behavior

Setting a boolean value, sets a boolean value

### Steps To Reproduce

```
up:
  comments: 'Sets  _hiddenInIndex to true for existing nodes.'
  migration:
    -
      filters:
        -
          type: NodeType
          settings:
            nodeType: 'Vendor.Docuemnt'
      transformations:
        -
          type: ChangePropertyValue
          settings:
            property: _hiddenInIndex
            newValue: true
```

### Environment

```markdown
- Flow: since ever
- Neos: since ever
- PHP: irrelevant
```
