### ISSUE TITLE
BUG: PropertyValue filter for migrations throws error

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-development-collection#3816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you use the `PropertyValue` filter for node migrations (introduced in Neos 7.0) the migration throws an QueryException.

<img width="307" alt="Screenshot 2022-06-09 at 12 10 42" src="https://user-images.githubusercontent.com/1014126/172823695-8b000829-181a-43c0-bcc8-bb5e3ae232f7.png">

### Expected Behavior

The Migration just runs successfully.

### Steps To Reproduce

Create a new migration that filters by property value.

```
up:
  comments: 'Migrate UserFeed view'
  migration:
    -
      filters:
        - type: 'NodeType'
          settings:
            nodeType: 'Neos.Neos:PluginView'
            withSubTypes: TRUE
        - type: 'PropertyValue'
          settings:
            propertyValue: 'UserFeed'
            propertyName: 'view'
      transformations:
        - type: 'ChangePropertyValue'
          settings:
            property: 'view'
            newValue: 'UserFeed-standard'

down:
  warnings: 'No down migration available'
```

I added this migration to the Neos.Demo package in Neos 7.0 and run the migration.
`./flow node:migrate --version=20220906110246`

### Environment

```markdown
- Flow: 7.0
- Neos: 7.0
- PHP: 7.4
```

### Anything else?

Tried that also with the latest Neos, and it also doesn't work ;)
We missed adding the new Feature to the Docs, BTW.
