### ISSUE TITLE
BUG: ChangePropertyValue should skip non string properties

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-development-collection#3817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you use the `ChangePropertyValue` for node migrations and have a boolean property, the migration will succeed, but adjusts the property wrong.

The migration does not skip the boolean property and writes `{current}` as new value.

### Expected Behavior

The migration just skips the boolean property or convert the value to a string and replace it.

### Steps To Reproduce

If you have a migration like that:
```
up:
  comments: 'Migrate boolean value test'
  migration:
    -
      filters:
        - type: 'NodeType'
          settings:
            nodeType: 'Neos.Demo:Document.NotFoundPage'
            withSubTypes: TRUE
      transformations:
        - type: 'ChangePropertyValue'
          settings:
            property: 'metaRobotsNoindex'
            search: 'true'
            replace: 'foo'

down:
  warnings: 'No down migration available'

```

The property will have the new value `{current}` in the DB.

### Environment

```markdown
- Flow: 6.3
- Neos: 5.3
- PHP: 7.4
```
