### ISSUE TITLE
BUG: Auto-created (document) child nodes are not published alongside the parent

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#3926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a NodeType with an auto-created (aka tethered) child node that extends `Neos.Neos:Document`, one can partially publish only the parent node leading to inconsistencies:

https://user-images.githubusercontent.com/307571/196664534-f9a25a67-8022-4797-a303-10471598e4bf.mov

### Expected Behavior

The publishing of a document node should publish auto-created child nodes (including document nodes) too

### Steps To Reproduce

1. Create two node types:

```yaml
'Some.Package:Document.ParentPage':
  ui:
    label: 'Parent'
  superTypes:
    'Neos.Neos:Document': true
  childNodes:
    'child':
      type: 'Some.Package:Document.ChildPage'
```
```yaml
'Some.Package:Document.ChildPage':
  ui:
    label: 'Child'
  superTypes:
    'Neos.Demo:Document.Page': true
```

2. Create an instance of the parent page
3. Publish just the parent page
4. Discard any pending changes

=> the child page will be removed

### Environment

```markdown
- Neos: all (5.3+)
```

### Anything else?

Fixing this will probably affect the workspaces modul as well because you should not be able to publish the auto-created child nodes individually:

![image](https://user-images.githubusercontent.com/307571/196664966-6c07f092-6f04-45a2-945a-c7ea094e8f18.png)

**Update:** The workspace module already disallows to publish only the parent page no matter whether the child documents are auto-created.

*Note:* This is slightly related to https://github.com/neos/neos-ui/issues/2282 but in this case I consider this a bug because it allows the editor to overrule the behavior. Allowing auto-created child nodes to be disabled is a decision of the integrator – furthermore in this case the child nodes are not just disabled but non-existent after publishing
