### ISSUE TITLE
BUG: Workspaces that are restricted through Policy.yaml are still shown in workspace lists

### ISSUE THREAD

**Issue by Benjamin-K** [neos/neos-development-collection#3963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When restricting a workspace through `Policy.yaml` (through `validateWorkspace`) so a user should not be able to see or publishing to this workspace, the workspace is still shown in the list in the Neos Content View in the top right and in the workspace list in the Neos backend module.

The `Policy.yaml` looks like this:

```yaml
privilegeTargets:
  'Neos\Flow\Security\Authorization\Privilege\Method\MethodPrivilege':
    'Example.Site:Workspace.ViewCustomWorkspace':
      label: 'Can view "custom workspace"'
      matcher: 'method(Neos\ContentRepository\Domain\Service\Context->validateWorkspace(workspace.name === "custom-workspace-1rs21"))'

roles:
  'Example.Site:CustomEditor':
    parentRoles: ['Neos.Neos:RestrictedEditor']
    # Does not have the required privilegeTarget
    # privileges:
    #   - privilegeTarget: 'Example.Site:Workspace.ViewCustomWorkspace'
    #     permission: GRANT
```

### Expected Behavior

If a workspace is restricted / could not be validated, the workspace should be removed from the list of workspaces in the Neos content view and the workspace module backend page.

### Steps To Reproduce

1. Create a new workspace.
2. Add the policy from above (with the newly created workspace). 
3. Create a new user with the newly created role. 
4. Check the mentioned workspace lists to see, that the workspace is still listed:
    - Top right in the Neos Content View.
    - The workspace list in the Workspaces backend module. 

### Environment

```markdown
- Flow: 7.3.9
- Neos: 7.3.10
- PHP:  8.1.11
```
