### ISSUE TITLE
BUG: `maximumFileSize` option of node property editor `ImageEditor` not supported since Neos 5.3

### ISSUE THREAD

**Issue by alexander-nitsche** [neos/neos-development-collection#4033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The official Neos documentation of 4.3, 5.3 and 7.3 states that there is an editor option `maximumFileSize` which can be defined to set an upper limit for the file size of uploads in the `ImageEditor`. The option value can be either of type integer or string (e.g. "1000000" or "1MB") - like the values of the php.ini settings `post_max_size` and `upload_max_filesize`. Code inspections have shown that this option was last used in Neos 4.3 and is ignored since Neos 5.3. 

Searching for "maximumFileSize" in Neos 4.3 lists 4 results, while in Neos 5.3 and 7.3 there are only 3 results. The 3 results are all YAML and documentation. The one additional result in 4.3 is found in https://github.com/neos/neos-development-collection/blob/4.3/Neos.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/FileUpload.js#L81 and contains the promising lines
```js
this._uploader = new plupload.Uploader({
	..
	max_file_size : this.get('maximumFileSize') ? this.get('maximumFileSize') : Configuration.get('maximumFileUploadSize'),
	..
});
```
`this.get('maximumFileSize')` was probably the value of the editor option, and the `Configuration.get('maximumFileUploadSize')` was the minimum of the php.ini values "post_max_size" and "upload_max_filesize".

### Expected Behavior

The node property editor option `maximumFileSize` should be considered in Neos > 4.3.

### Steps To Reproduce

1. In Neos 7.3, configure a node property using the image editor with a maximum file upload size of 100 KB, e.g.
    ```yaml
    backgroundImage:
      type: Neos\Media\Domain\Model\ImageInterface
      defaultValue: ''
      ui:
        label: 'backgroundimage'
        reloadIfChanged: true
        inspector:
          group: 'Settings'
          editor: 'Neos.Neos/Inspector/Editors/ImageEditor'
          editorOptions:
            maximumFileSize: '100KB'
    ```
2. Upload an image with a file size larger than 100KB using the image editor in the Neos UI.
3. Confirm that the operation was successful.

### Environment

```markdown
- Flow: 5.3, 7.3
- Neos: 5.3, 7.3
- PHP: 7.4
```

### Anything else?

The problem appeared when PHPStorm's Neos plugin complained about a string type value for the `maximumFileSize` option, while it only accepts integers. So began the investigation of why the expectations of the plugin and the documentation differed.
