### ISSUE TITLE
BUG: Count Validator showing wrong error message

### ISSUE THREAD

**Issue by ghost** [neos/neos-development-collection#4034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when you have type: references and add a count validator the error message in backend is shown without the minimum and maximum integers that are in the yaml
`
The count must be between {minimum} and {maximum}.
`

Example from my Project:
```
products:
      type: references
      defaultValue: []
      ui:
        label: 'Products'
        reloadIfChanged: true
        inspector:
          group: 'products'
          hidden: 'ClientEval:node.properties.listType != "static"'
          editorOptions:
            nodeTypes:
              - 'Acme.Blog:Test.Test'
      validation:
        'Neos.Neos/Validation/CountValidator':
          minimum: '0'
          maximum: '3'
```

### Expected Behavior

When you have type: references and add a count validator the error message in backend is shown with the minimum and maximum integers that are in the yaml
`
The count must be between 0 and 3.
`

### Steps To Reproduce

1. create property with type references
2. Neos.Neos/Validation/CountValidator with minimum of 0 and maximum 3. (the numbers can of course be different)
3. go into the backend and put 4 references in

### Environment

```markdown
- Flow: 8.1.2
- Neos: 8.1.2
- PHP: 8.1
```
