### ISSUE TITLE
BUG: PdoBackend setup with custom table name fails

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`./flow cache:setup` fails with:
> ERROR: Could not create cache tables with DSN "[...]". PDO error: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cache' already exists

### Expected Behavior

The configured tables for cache entries and tags should be created, or the creation silently skipped if they already exist

### Steps To Reproduce

Configure a cache to use the `PdoBackend` with a custom table name:

```yaml
Flow_Session_Storage:
  backend: Neos\Cache\Backend\PdoBackend
  backendOptions:
    dataSourceName: 'mysql:host=%env(string):DATABASE_HOST%;dbname=%env(string):DATABASE_NAME%;charset=utf8mb4'
    cacheTableName: 'cache_session'
    tagsTableName: 'cache_session_tags'
    username: '%env(string):DATABASE_USERNAME%'
    password: '%env(string):DATABASE_PASSWORD%'
```

Run

```
./flow cache:setup Flow_Session_Storage
```

### Environment

```markdown
- Flow: all supported (5.3 - 8.2)
```

### Anything else?

The issue is, that the `CREATE TABLE` statements are hard-coded in corresponding `.sql` files and that the configured `cacheTableName` and `tagsTableName` options are ignored.
