### ISSUE TITLE
9.0 BUG: ImageInterface

### ISSUE THREAD

**Issue by Vinh911** [neos/neos-development-collection#4062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After attempting to delete an image in the ImageEditor, an error is generated with the message:

`Property "image" cannot be set to a value of type "string", it must be of type "Neos\Media\Domain\Model\ImageInterface".`

 The error appears immediately after clicking "Apply".

### Expected Behavior

The deletion of the image in the ImageEditor should be successfully executed without any error messages. The changes should be applied as expected.

### Steps To Reproduce

1. Create an element or page with an ImageEditor
2. Add an Image to the editor and apply changes
3. Delete the image in the inspector
4. Click "Apply"

### Environment

```markdown
- Flow: 8.2-dev
- Neos:9.0-dev
- PHP: 8.1
```
property config:
```
  properties:
    pageTeaserImage:
      type: 'Neos\Media\Domain\Model\ImageInterface'
      ui:
        label: 'Teaser-Bild'
        reloadIfChanged: true
        inspector:
          group: 'pageTeaser'
```

property config:
