### ISSUE TITLE
BUG: Function not found lower(jsonb): Node Migration

### ISSUE THREAD

**Issue by amtee** [neos/neos-development-collection#4080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I wrote a node migration using filters for property values. 

```
[...]
    filters:
        -
          type: 'PropertyValue'
          settings:
            propertyName: 'hierarchy'
            propertyValue: 'p'
      transformations:
        -
          type: 'ChangeNodeType'
          settings:
            newType: 'Neos.NodeTypes:Text'
        -
          type: 'RenameProperty'
          settings:
            from: 'title'
            to: 'text'
[...]
```

On execution I get the following exception: 

```sql
An exception occurred while executing 'SELECT n0_.persistence_object_identifier AS persistence_object_identifier_0, n0_.version AS version_1, n0_.pathhash AS pathhash_2, [....] FROM neos_contentrepository_domain_model_nodedata n0_ WHERE n0_.nodetype IN ('Neos.NodeTypes:Headline') AND LOWER(n0_.properties) LIKE ?' with params ["%\"hierarchy\": \"p\"%"]:

SQLSTATE[42883]: Undefined function: 7 ERROR:  function lower(jsonb) does not exist
LINE 1: ...E n0_.nodetype IN ('Neos.NodeTypes:Headline') AND LOWER(n0_....                                                             
```

### Expected Behavior

I expect the migration to work as configured. 

### Steps To Reproduce

- Create a node migration for any NodeType with a filter of type **property**  e.g. `PropertyValue `
- Try to run the migration

Probably you need to adjust the properties a little bit.

```
up:
  comments: 'Migrate the paragraph headline workaround to node type text'
  migration:
    -
      filters:
        -
          type: 'NodeType'
          settings:
            nodeType: 'Neos.NodeTypes:Headline'
        -
          type: 'PropertyValue'
          settings:
            propertyName: 'hierarchy'
            propertyValue: 'p'
      transformations:
        -
          type: 'ChangeNodeType'
          settings:
            newType: 'Neos.NodeTypes:Text'
        -
          type: 'RenameProperty'
          settings:
            from: 'title'
            to: 'text'
        -
          type: 'RemoveProperty'
          settings:
            property: 'hierarchy'
        -
          type: 'RemoveProperty'
          settings:
            property: 'size'
down:
  comments: 'No down migration available'
```

### Environment

```markdown
- Flow: 7.3.10
- Neos: 7.3.11
- PHP: 8.1.15
- Postgres: 14.6 || 13.9
```
