### ISSUE TITLE
BUG: "Could not connect to database" error in setup with env

### ISSUE THREAD

**Issue by erkenes** [neos/neos-development-collection#4145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If envs are set in the configuration file to connect to the database, the setup shows that the connection cannot be established.
If I click "Next" everything works.

![image](https://user-images.githubusercontent.com/8766722/228191402-a4ecb85e-d9cf-4373-96a8-015167b86d67.png)

```yaml
Neos:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: '%env:MYSQL_DATABASE%'
        user: '%env:MYSQL_USER%'
        password: '%env:MYSQL_PASSWORD%'
```

### Expected Behavior

The ENVs should be resolved to use the appropriate content rather than plain text for the link.

### Steps To Reproduce

1. Create a Settings.yaml and set the envs.
```yaml
Neos:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: '%env:MYSQL_DATABASE%'
        user: '%env:MYSQL_USER%'
        password: '%env:MYSQL_PASSWORD%'
```
2. Open the Neos Setup and go to the "Configure database" page

### Environment

```markdown
- Flow: 8.0.7
- Neos: 8.0.8
- PHP: 8.1
```
