### ISSUE TITLE
BUG: Custom editPreviewMode (or Renderer / renderPath?) Not working

### ISSUE THREAD

**Issue by Benjamin-K** [neos/neos-development-collection#4175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a new editPreviewMode with a custom fusionRenderingPath, the rendering will not work as expected and result in memory limits being reached. 

I'm trying to integrate a custom mode that hides some nodes if they match a condition (like "Do not show hidden elements" as in #2934 ).

Right now I'm not 100 % sure if the error comes from the new mode or from the Neos.Fusion:Renderer. I'll add further information as soon I investigated further on this.

### Expected Behavior

The new mode is rendered as expected with the nodes that match the condition not being shown.

### Steps To Reproduce

Create a new editPreviewMode:

Settings.yaml
```
Neos:
   Neos:
     userInterface:
       editPreviewModes:
         custom:
           isEditingMode: true
           isPreviewMode: false
           fusionRenderingPath: "custom"
           title: "Custom"
           position: "after inPlace"
```

Fusion:
```
 custom = Neos.Fusion:Renderer {
     renderPath = '/root'

     prototype(Neos.Fusion:Component) {
         @if.isVisibleInCustom = ${!node.hidden} # Use .hidden for testing
     }
 }
```

Try to switch to that mode that should not show any hidden elements any more.

### Environment

```markdown
- Flow: 8.2.0
- Neos: 8.2.3
- PHP: 8.1.16
```
