### ISSUE TITLE
BUG: DateTime Editor doesn't show loaded datetimes

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#4192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I select a datetime with the datetime editor and apply this, the datetime editor got empty or reset to its default value.

The selected datetime got stored. I see it in the events and also in the node projection.

The payload of the reponse contains all properties of the node, but the datetime property is `null` instead of the selected and stored value. Also a page refresh doesn't load the datetime into the editor.

In this case the default value is set to "today midnight", so it shows always the current date after apply. But the content itself shows the selected date, which proofs that the date got stored properly.
![image](https://user-images.githubusercontent.com/13046100/232052562-10cb6d5f-6b1f-4a26-bb5f-5b6bf98a5594.png)

### Expected Behavior

The datetime editor should show the selected datetime value.

### Steps To Reproduce

1. Create a node with a datetime. E.g:

```
'Neos.Demo:Document.Homepage':
  properties:
    publishingDate:
      type: DateTime
      ui:
        label: 'Publishing Date'
        inspector:
          group: 'document'
          position: 10
```
2. Set a datetime
3. Apply

### Environment

```markdown
- Flow: 8.3
- Neos: 9.0
- PHP: 8.1
```
