### ISSUE TITLE
BUG: Running Neos in a subdirectory

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4238]
We have tried to run Neos in a subdirectory, and encountered various issues.
The main culprit is "UriBuilder::build", where the following logic happens (slightly shortened)

```
   $uriPathPrefix = RequestInformationHelper::getScriptRequestPath($httpRequest) . $uriPathPrefix;
   $resolveContext = new ResolveContext($this->baseUriProvider->getConfiguredBaseUriOrFallbackToCurrentRequest($httpRequest), $arguments, $this->createAbsoluteUri, $uriPathPrefix, $routeParameters);
   $resolvedUri = $this->router->resolve($resolveContext);
```

at least in our case (while we debugged it) when generating absolute URLs, the URI path prefix
was applied TWICE: once from $uriPathPrefix, the other from the auto-detected (or configured)
base URL.

It is pretty hard to clean these code paths; but the following workaround seems to work:

1) we can not change the calculation of $uriPathPrefix from above (there is no
   config flag influencing this)
2) => thus, we explicitly need to set the base URL to "<host>/"
3) then, the URL builder works as expected, but persistent resources are missing the URL Prefix
3a) we can configure the URL path prefix for both the persistentResourcesTarget and the
     staticResourcesTarget to include the prefix.

This seems to work so far, but it is really hacky.

**Configuration:**

```yaml
Neos:
  Flow:
    http:
      #
      baseUri: 'https://my.host.com/'
    resource:
      targets:
        # Target for publishing static resources to the local web directory
        localWebDirectoryStaticResourcesTarget: { targetOptions: { baseUri: 'subfolder/_Resources/Static/Packages/' } }
        # Target for publishing persistent resources to the local web directory
        localWebDirectoryPersistentResourcesTarget: { targetOptions: { baseUri: 'subfolder/_Resources/Persistent/' } }
```

**.htaccess:**
```
...
RewriteBase /subfolder
...
```

### Environment

```markdown
- Flow: 8.x
- Neos: 8.x & 9.x
```

### Is there an existing issue for this?

- [X] I have searched the existing issues
