### ISSUE TITLE
9.0 BUG: defaultUriSuffix is not working

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#4271]
If I set up the defaultUriSuffix  as in Neos 8.x, the routing doesn't appends the urls with the given suffix.

```
Neos:
  Flow:
    mvc:
      routes:
        'Neos.Neos':
          variables:
            defaultUriSuffix: '.html'
```

This is caused ny the new `EventSourcedFrontendNodeRoutePartHandler`, which internally uses the option `uriSuffix`:

https://github.com/neos/neos-development-collection/blob/52f6154cfc87da8de3bd4e960929381a252a9358/Neos.Neos/Classes/FrontendRouting/EventSourcedFrontendNodeRoutePartHandler.php#L320

But the routing configuration maps `defaultUriSuffix` to the option `uriPathSuffix`:

https://github.com/neos/neos-development-collection/blob/52f6154cfc87da8de3bd4e960929381a252a9358/Neos.Neos/Configuration/Routes.Frontend.yaml#L19-L19
