### ISSUE TITLE
BUG: node properties with a `false` value are incorrectly stored as empty value in site exports

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-development-collection#4296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In https://github.com/neos/neos-development-collection/blob/fd5b9bcc7e61893b087d49e3b4cd12e7efcf1b4b/Neos.ContentRepository/Classes/Domain/Service/ImportExport/NodeExportService.php#L420 the value is converted to a string. 

This turns `false` into `''` which is written to the xml file. Importing the data again skips the property as it's "empty".

### Expected Behavior

As `true` is converted to `1`, `false` should be converted to `0`.

I adjusted to code for this case in a test and the resulting export also properly worked and set the node property correctly to `false` again after the import.

### Steps To Reproduce

Add a new property to a document node in the Neos.Demo like this:

```yaml
properties:
    someBool:
      type: boolean
      defaultValue: false
      ui:
        label: 'Some bool'
        inspector:
          group: document
```

Run `./flow node:repair` to set the values for all documents.
Export via `./flow site:export --package-key Neos.Demo` and check the resulting XML and see that the property shows up in the resulting `Sites.xml` with an empty string.

Reimport it again via `./flow site:import --package-key Neos.Demo` will then drop the property from all nodes as it was empty in the xml.

### Environment

```markdown
- Flow: 7.3
- Neos: 7.3 (actually at least since 5.3)
- PHP: 7.4
```
