### ISSUE TITLE
9.0: Property "something" cannot be set to a value of type "array", must be of type "array<string>".

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4307]
<img width="557" alt="image" src="https://github.com/neos/neos-development-collection/assets/85400359/64663479-4c2f-4116-8318-c8dc734746d2">

```
Property "something" cannot be set to a value of type "array", must be of type "array<string>".
```

array of only allows classnames currently:
https://github.com/neos/neos-development-collection/blob/31cb00aa0bb513c9e8878807a0de23772f50d992/Neos.ContentRepository.Core/Classes/Infrastructure/Property/PropertyType.php#L198-L208

Reproduce:

create a nodeType like
```yaml
'Neos.Demo:Content.Headline':
  superTypes:
    'Neos.Neos:Content': true
  ui:
    label: Test
  properties:
    something:
      type: array<string>
      ui:
        label: "Something"
        inspector:
          group: default
          editor: Neos.Neos/Inspector/Editors/SelectBoxEditor
          editorOptions:
            allowEmpty: true
            multiple: true
            values:
              something1:
                label: something1
              something2:
                label: something2
              something3:
                label: something3
              something4:
                label: something4
              something5:
                label: something5
```

set the property in the ui.

using type array works.
