### ISSUE TITLE
TASK: 9.0 Test childNode name transliteration in yaml

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4362]
Do we still want to allow illegal childNode names in the nodeTypes config like in the old cr?

Like

```yaml
childNodes:
  'äüfäewfü':
    type: "Foo:Bla"
  '':
   type: "Bar:Bung"
```

Then we must adjust to NodeName::transliterate
https://github.com/neos/neos-development-collection/blob/fb89fb65cb133c1c48c4d82d553fa23e5951468c/Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php#L284

**Comment by mhsdesign** [comment]
I was wrong, the code just didnt read well ^^, i tested it and it works:

```yaml
'Flowpack.NodeTemplates:Content.NodeNames':
  superTypes:
    'Neos.Neos:ContentCollection': true
  childNodes:
    my-node:
      type: 'Flowpack.NodeTemplates:Content.Text'
    fooBar:
      type: 'Flowpack.NodeTemplates:Content.Text'
    ö:
      type: 'Flowpack.NodeTemplates:Content.Text'
    'äBla北京=.§$Hä':
      type: 'Flowpack.NodeTemplates:Content.Text'
    '':
      type: 'Flowpack.NodeTemplates:Content.Text'
```

we use `transliterateFromString` already in `getAutoCreatedChildNodes` so technically its not the `$rawNodeName` but just `$stringNodeName` -> but lets get not lost in details
