### ISSUE TITLE
Allow defaultUriSuffix to be specified per Site

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4389]
Currently the `defaultUriSuffix` is a global setting:

```yaml
Neos:
  Flow:
    mvc:
      routes:
        'Neos.Neos':
          variables:
            'defaultUriSuffix': '.html'
```

This makes it impossible to have a different configuration per site in a multi site installation and it makes it harder to write automated tests covering multiple different configurations.

To allow the setting to be site specific it could be configured like this:

```yaml
Neos:
  Neos:
    sites:
      '<someSiteId>':
        'defaultUriSuffix': '.html'
```

> **Note**
> For b/c we should probably still evaluate `Neos.Flow.mvc.routes.'Neos.Neos'.variables.defaultUriSuffix` as fallback

> **Warning**
> We have to make sure that the option is applied even for cross-site links!
