### ISSUE TITLE
BUG: Undefined array key "type" when apply node migration

### ISSUE THREAD

**Issue by crydotsnake** [neos/neos-development-collection#4461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have created a test node migration:

```yaml
comments: 'Migration description'
migration:
  -
    filters:
      -
        type: 'NodeType'
        settings:
          nodeType: 'Neos.Demo:Content.Text'
    transformations:
      -
        type: AddNewProperty
        settings:
          newPropertyName: test
```

And when apply the migration:

```bash
./flow nodemigration:migrate --version 20230829161853
```

it returns:

```
Comments
  Migration description
Warning: Undefined array key "type" in /home/USERNAME/git/neos-development-9/Packages/Neos/Neos.ContentRepository.NodeMigration/src/Transformation/AddNewPropertyTransformationFactory.php line 38

  Type: Neos\Flow\Error\Exception
  Code: 1
  File: Packages/Framework/Neos.Flow/Classes/Error/ErrorHandler.php
  Line: 81

Open Data/Logs/Exceptions/2023082917392611ac67.txt for a full stack trace.
```

### Line:

https://github.com/neos/neos-development-collection/blob/bb8bc836163bb6b0f104ec3b102f7c81302cca02/Neos.ContentRepository.NodeMigration/src/Transformation/AddNewPropertyTransformationFactory.php#L38

### Exception

```
Exception #1 in line 38 of /home/USERNAME/git/neos-development-9/Packages/Neos/Neos.ContentRepository.NodeMigration/src/Transformation/AddNewPropertyTransformationFactory.php: Warning: Undefined array key "type" in /home/USERNAME/git/neos-development-9/Packages/Neos/Neos.ContentRepository.NodeMigration/src/Transformation/AddNewPropertyTransformationFactory.php line 38

16 Neos\Flow\Error\ErrorHandler::handleError()
15 Neos\ContentRepository\NodeMigration\Transformation\AddNewPropertyTransformationFactory::build()
14 Neos\ContentRepository\NodeMigration\Transformation\TransformationsFactory::buildTransformationObject()
13 Neos\ContentRepository\NodeMigration\Transformation\TransformationsFactory::buildTransformation()
12 Neos\ContentRepository\NodeMigration\NodeMigrationService::executeSubMigrationAndBlock()
11 Neos\ContentRepository\NodeMigration\NodeMigrationService::executeMigration()
10 Neos\ContentRepositoryRegistry\Command\NodeMigrationCommandController_Original::migrateCommand()
9 Neos\Flow\Cli\CommandController_Original::callCommandMethod()
8 Neos\Flow\Cli\CommandController_Original::processRequest()
7 Neos\Flow\Cli\Dispatcher_Original::dispatch()
6 Neos\Flow\Cli\CommandRequestHandler::Neos\Flow\Cli\{closure}()
5 Closure::__invoke()
4 Neos\Flow\Security\Context_Original::withoutAuthorizationChecks()
3 Neos\Flow\Cli\CommandRequestHandler::handleRequest()
2 Neos\Flow\Core\Bootstrap::run()
1 require("/home/USERNAME/git/neos-development-9/Packages/Framework/Neos.Flow/Scripts/flow.php")
```

### Expected Behavior

Migration should be applyed without any errors.

### Steps To Reproduce

1. Add a new property to a NodeType:
 
```yaml
test:
  type: boolean
  defaultValue: true
  ui:
    label: Boolean
```
2. Create your node migration:

```yaml
comments: 'Migration description'
migration:
  -
    filters:
      -
        type: 'NodeType'
        settings:
          nodeType: 'Neos.Demo:Content.Text'
    transformations:
      -
        type: AddNewProperty
        settings:
          newPropertyName: test
```

3. Execute the migration:

```bash
./flow nodemigration:migrate --version 20230829161853
```

### Environment

```markdown
- Flow: 9.0.x-dev
- Neos: 9.0.x-dev
- PHP: 8.2
```
