### ISSUE TITLE
9.0 Should `_hidden.defaultValue = true` work?

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4484]
```yaml
properties:
    _hidden:
      defaultValue: true
```

this seems to work in 8.3 (someone in slack tried it)

related https://github.com/neos/neos-development-collection/issues/4208
