### ISSUE TITLE
BUG: Moved NodeVariants can't be migrated from Neos 8

### ISSUE THREAD

**Issue by grizooo** [neos/neos-development-collection#4504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
Exporting node data...
  Exported 25540 events

Importing assets...
  Imported 0 Assets and 1 Image Variant. Errors: 0

Importing events...
  Imported 25540 events into stream "ContentStream:97f1433f-c1d2-4385-8141-f857bf144592"


Replaying projections
Failed to update and commit highest applied sequence number for subscriber "Neos\ContentGraph\DoctrineDbalAdapter\DoctrineDbalContentGraphProjection".
Please run
Neos\EventStore\DoctrineAdapter\DoctrineCheckpointStorage::setup()

  Type: Neos\EventStore\Exception\CheckpointException
  Code: 1652279375
  File: Packages/Libraries/neos/eventstore-doctrineadapter/src/DoctrineCheckpointSt
        orage.php
  Line: 82

Nested exception:
Transaction commit failed because the transaction has been marked for rollback only.

  Type: Doctrine\DBAL\ConnectionException
  File: Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/ConnectionException.php
  Line: 15

Nested exception:
Event Neos\ContentRepository\Core\Feature\NodeVariation\Event\NodePeerVariantWasCreated could not be applied: Target parent node not found.

  Type: Neos\ContentGraph\DoctrineDbalAdapter\Domain\Projection\EventCouldNotBeAppl
        iedToContentGraph
  Code: 1645315274
  File: Packages/Neos/Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/E
        ventCouldNotBeAppliedToContentGraph.php
  Line: 41

```

### Expected Behavior

Migration done whithout errors.

### Steps To Reproduce

```
Neos:
  Flow:
    i18n:
      defaultLocale: en
  ContentRepository:
    contentDimensions:
      language: # name of the dimension, can be anything
        label: Languages # display in UI
        icon: icon-language # icon for UI

        # The default dimension that is applied when creating nodes without specifying a dimension
        default: en_US

        # The default preset to use if no URI segment was given when resolving languages in the router
        defaultPreset: en_US
        presets:
          en_US:
            label: English
            values:
              - en_US
            uriSegment: ''
          de:
            label: Deutsch
            values:
              - de
            uriSegment: 'de'
          es:
            label: Español
            values:
              - es
            uriSegment: 'es'
          fr:
            label: Français
            values:
              - fr
            uriSegment: 'fr'
          it:
            label: Italiano
            values:
              - it
            uriSegment: 'it'
          br:
            label: Português
            values:
              - br
            uriSegment: 'br'
          ru:
            label: Pусский
            values:
              - ru
            uriSegment: 'ru'
  Neos:
    userInterface:
      defaultLanguage: en
      translation:
        autoInclude:
          Paessler.PaesslerCom:
            - Main
            - 'NodeTypes/*'

```

### Environment

```markdown
- Flow: 8.3.3
- Neos: 8.3.4
- PHP: 8.2
```

### Anything else?

We tried to remove nodes without parents first -> no success.
We started node migration to set node without language to default language (suggested from bernhard) -> no success

```
up:
  comments: 'Migrate from no node dimensions to default dimension values.'
  migration:
    -
      filters:
        -
          type: 'DimensionValues'
          settings:
            dimensionValues: []
      transformations:
        -
          type: 'SetDimensions'
          settings:
            dimensionValues: []
            addDefaultDimensionValues: true

down:
  comments: 'Migrate nodes with default dimensions to no migrations.'
  migration:
    -
      filters:
        -
          type: 'DimensionValues'
          settings:
            dimensionValues: []
            filterForDefaultDimensionValues: true
      transformations:
        -
          type: 'SetDimensions'
          settings:
            dimensionValues: []
            addDefaultDimensionValues: false

```
