### ISSUE TITLE
Node properties vs references confusion

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4549]
The difference of `q(node).property("reference")`  vs `node.properties.reference` causes [confusion](https://neos-project.slack.com/archives/C3MCBK6S2/p1694700146148369).

In todays weekly we discussed some potential ways to improve the DX:

- [ ] Introduce Deprecation Log
  - This might be a good idea _in general_ but in this specific case we could use it to log usages of `q(node).property("<reference-name>")`.
One alternative would be to throw an exception in this case – but that is rather flaky in Fusion land
- [ ] Throw exception when trying to access references via properties through PHP API
  - `$node->getProperty("reference")` currently returns `null` but we could also throw an exception that explains how to use `FindReferences` instead
- [x] Deprecated/Remove `reference(s)` property type in NodeType schema (see below)
- [x] NodeType::getProperties would need to split up in NodeType::getReferences

References are no properties with Neos 9.
This is easy to communicate, but it makes "reference properties" even weirder, so we should strive to replace:

```yaml
'Some.Package:SomeNodeType':
  properties:
    'text':
      type: string
   'someReference':
      type: reference
          properties:
            'foo':
              type: string
```

with

```yaml
'Some.Package:SomeNodeType':
  properties:
    'text':
      type: string
  references:
   'someReference':
        properties:
          'foo':
            type: string
```
