### ISSUE TITLE
Site Config Presets

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4582]
Similar to ContentRepository presets it might be useful to be able to define presets for site configurations and potentially ship a default preset with `Neos.Neos`.

So instead of:

```yaml
Neos:
  Neos:
    sites:
      '*':
        uriPathSuffix: '.html'
        contentRepository: default
        contentDimensions:
          resolver:
            factoryClassName: Neos\Neos\FrontendRouting\DimensionResolution\Resolver\AutoUriPathResolverFactory
```

we could have something like:
```yaml
Neos:
  Neos:
    sitePresets:
      'default':
        uriPathSuffix: '.html'
        contentRepository: default
        contentDimensions:
          resolver:
            factoryClassName: Neos\Neos\FrontendRouting\DimensionResolution\Resolver\AutoUriPathResolverFactory
    sites:
      'my-site-node-name':
        preset: 'default'
```
