### ISSUE TITLE
BUG: out-of-band-rendering throws an error when creating a new childnode for a content-collection

### ISSUE THREAD

**Issue by c4ll-m3-j4ck** [neos/neos-development-collection#4622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating a new node as a child-node of a content-collection causes the ui to show an error that no `nearestContentCollection` could be found.

This seems to happen while the backend tries to provide the out-of-band-rendering to show the newly created node.

The node is created correctly and a reload shows the new node without issues.

### Expected Behavior

The new node should be shown and no error should be shown.

### Steps To Reproduce

Create a new child-node inside a content-collection that is the child of a document node. The issue does not seem to appear if you create a child-node of a content-node.

### Environment

```markdown
- Flow: neos/flow-development-collection": "9.0.x-dev"
- Neos: neos/neos-development-collection": "9.0.x-dev"
- PHP: 8.2.9
```

### Anything else?

Exception log:
[202310161144552396b6.txt](https://github.com/neos/neos-development-collection/files/12915944/202310161144552396b6.txt)

Document-NodeType configuration:
```
'Acme.Site:Document.Page':
  superTypes:
    'Neos.Neos:Document': true
  ui:
    icon: file
    label: 'Acme.Site Page'
  childNodes:
    main:
      type: 'Neos.Neos:ContentCollection'
```
