### ISSUE TITLE
Consistent node type behavior regarding property unset and child node unset

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4722]
As shown here (by the new tests) https://github.com/neos/neos-development-collection/pull/4620 node property unset via `~` does not work but is silently ignored.

```yaml
Some.NodeType:
  superTypes:
    Some.SuperNodeType: true
  properties:
    inheritedProperty: ~ # noop
```

instead its only possible to change the type or set it to hidden. A shortcut for this would be:

```yaml
Some.NodeType:
  superTypes:
    Some.SuperNodeType: true
  properties:
    inheritedProperty: {}
``` 

see https://github.com/neos/neos-development-collection/pull/4620#discussion_r1360407119 we are not sure if we like that one can change the type of a property or disable it in the inspector but its possible.

---------

in contraire, unsetting a child node is allowed:

```yaml
Some.NodeType:
  superTypes:
    Some.SuperNodeType: true
  childNodes:
    main: ~
```
