### ISSUE TITLE
FEATURE: Extensibility for uriPathSegment

### ISSUE THREAD

**Issue by lorenzulrich** [neos/neos-development-collection#4835]
### Is there an existing issue for this topic?

- [X] I have searched the existing issues

### Description

Currently, the uriPathSegment generation cannot be configured and it is quite hard to replace it since the `NodeUriPathSegmentGenerator` does not implement an interface. It would be nice to make it configurable on the Node Type definition level.

### Possible Solution

I suggest an approach using EEL similar to the node label or node templates, of course naming and configuration should be discussed:

```
'My.Site:Document.NewsPage':
  options:
    uriPathSegmentGenerator:
      # Example: my-great-news-a1b2c3d4
      uriPathSegmentConfiguration: '${data.title + '-' + String.substr(String.sha1(data.title), 0, 8)}'
```

Or:

```
'My.Site:Document.NewsPage':
  options:
    uriPathSegmentGenerator:
      # Example: my-great-news-a1b2c3d4
      uriPathSegmentConfiguration: '${data.title + '-' + Date.format(data.date, 'Y-m-d')}'
```

This configuration would override the default generation.
