### ISSUE TITLE
BUG: a new language present with different key and value ends in an exception

### ISSUE THREAD

**Issue by iseries** [neos/neos-development-collection#4857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding a new language present with a different key and value an Exception is thrown.

Exception
```
An exception was thrown while Neos tried to render your page

Warning: Undefined array key "en_US" in /var/www/mysite.local/neos/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Neos_Fusion_DimensionsMenuItemsImplementation.php line 111

root<Neos.Fusion:Case>/
 documentType<Neos.Fusion:Matcher>/
  element<Rehme.Site:Document.Homepage>/
   renderer<Rehme.Site:Document.Layout.Base>/
    renderer<Neos.Neos:Page>/
     head<Neos.Fusion:Join>/
      alternateLanguageLinks<Neos.Seo:AlternateLanguageLinks>/
       renderer<Neos.Fusion:Loop>/
        items<Neos.Neos:DimensionsMenuItems>/
```
Log:
```
Exception #1 in line 111 of /var/www/mysite.local/neos/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Neos_Fusion_DimensionsMenuItemsImplementation.php: Warning: Undefined array key "en_US" in /var/www/mysite.local/neos/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Neos_Fusion_DimensionsMenuItemsImplementation.php line 111

84 Neos\Flow\Error\ErrorHandler::handleError()
83 Neos\Neos\Fusion\DimensionsMenuItemsImplementation_Original::Neos\Neos\Fusion\{closure}()
82 array_walk()
81 Neos\Neos\Fusion\DimensionsMenuItemsImplementation_Original::buildItems()
80 Neos\Neos\Fusion\AbstractMenuItemsImplementation::getItems()
79 Neos\Neos\Fusion\AbstractMenuItemsImplementation::evaluate()
78 Neos\Fusion\Core\Runtime_Original::evaluateObjectOrRetrieveFromCache()
77 Neos\Fusion\Core\Runtime_Original::evaluate()
[...]
5 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
4 Neos\Flow\Http\Middleware\StandardsComplianceMiddleware_Original::process()
3 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
2 Neos\Flow\Http\RequestHandler::handleRequest()
1 Neos\Flow\Core\Bootstrap::run()


HTTP REQUEST:
target: /
Upgrade-Insecure-Requests: 1
Cookie: Neos_Session=PeptXzhYdFRJNTOOEX1AzA1Iwoc5nQ58
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0
Host: mysite.local:8080

PHP PROCESS:
Inode: 24520080
PID: 64742
UID: 1000
GID: 33
User: arjuna
```

### Expected Behavior

Based on the [documentation](https://docs.neos.io/guide/manual/content-repository/content-dimensions/multiple-languages#configuring-a-bilingual-site), it should be possible to define a different key and value.

### Steps To Reproduce

Current Settings:
```
Neos:
  Neos:
    routing:
      supportEmptySegmentForDimensions: true
  ContentRepository:
    contentDimensions:
      language:
        label: 'Sprache'
        default: de
        defaultPreset: de
        presets:
          de:
            label: 'Deutsch'
            values:
              - de
            uriSegment: ''
```
Extend it with:
```
          en:
            label: 'Englisch'
            values:
              - en_US
            uriSegment: 'en'
```
Execute:
`./flow flow:cache:flush` and `./flow node:migrate 20150716212459`

Open the frontend.

### Environment

```markdown
- Neos: 8.3.9
- PHP: 8.2.15
```

### Anything else?

Denny Lubitz noticed in slack ([see here](https://neos-project.slack.com/archives/C050C8FEK/p1706453750853599?thread_ts=1706451642.897519&cid=C050C8FEK)) that there is a hard convention in the DimensionsMenuItemsImplementation, that key and label needs to be the same: https://github.com/neos/neos-development-collection/blob/8.3/Neos.Neos/Classes/Fusion/DimensionsMenuItemsImplementation.php#L111C81-L111C95
