### ISSUE TITLE
Performance ESCR tests. Disabling Neos.Neos `catchUpHooks` speeds up tests

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4878]
Related: https://github.com/neos/neos-development-collection/pull/4750

running

```
composer run test:behat-cli -- -c 'Neos.ContentRepository.BehavioralTests/Tests/Behavior/behat.yml.dist'
```

takes 28 seconds currently.

When disabling the unneeded (for those tests) `RouterCacheHookFactory` and `GraphProjectorCatchUpHookForCacheFlushingFactory` neos hooks it improves to 21 seconds.

And also excluding the `PendingChangesProjection` will make it to about 19 seconds.

**Comment by kitsunet** [comment]
Fine for me, the question is at what point the tests are no longer representative of the real world. Does the hook have dedicated tests for example?

**Comment by mhsdesign** [comment]
With https://github.com/neos/neos-development-collection/pull/4904 i allow a workaround to do this locally which seems fine for now?

```yaml
Neos:
  ContentRepositoryRegistry:
    presets:
      'default':
        projections:
          'Neos.Neos:DocumentUriPathProjection':
            catchUpHooks:
              'Neos.Neos:FlushRouteCache': ~
          'Neos.Neos:PendingChangesProjection': ~
          'Neos.ContentRepository:ContentGraph':
            catchUpHooks:
              'Neos.Neos:FlushContentCache': ~
          'Neos.Neos:AssetUsage': ~
```

do you agree?
