### ISSUE TITLE
BUG: Neos\Media\Domain\Model\Adjustment\CropImageAdjustment crop window for image variants is too big

### ISSUE THREAD

**Issue by Vinh911** [neos/neos-development-collection#4935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the crop feature for image variants in the media center, the save button becomes unreachable if the browser is in full screen mode. This issue occurs when working with an image that has dimensions of 2715px x 2715px and an variant preset with aspect ratio of 4:1.

Screenshot: https://ibb.co/ZJz6nys

### Expected Behavior

The crop window should resize properly to accommodate the image, ensuring that the save button is always accessible.

### Steps To Reproduce

1. set the variantPreset aspect ratio of 4:1 in the media center
2. Upload an image with dimensions of 2715px x 20715px
3. use the browser in full screen
4. G to the variants section and attempt to crop the 4:1 version of the image

### Environment

```markdown
- Flow: 8.2-dev
- Neos: 9.0-dev
- Neos-Ui: 9.0-dev
- PHP: 8.1
````

Settings.Media.yaml:
```
Neos:
  Media:
    Browser:
      features:
        variantsTab:
          enable: true
    autoCreateImageVariantPresets: true
    variantPresets:
      'Vbg.Site:GeneralImageVariants':
        label: 'Allgemeine Bildvarianten'
        mediaTypePatterns: [ '~image/(jpe?g|png)~' ]
        variants:
          '4-1':
            label: '4-1'
            description: 'Bildverhältnis 4:1'
            adjustments:
              crop:
                type: 'Neos\Media\Domain\Model\Adjustment\CropImageAdjustment'
                options:
                  aspectRatio: '4:1'
```

### Anything else?

The problem appears in Version 7.x aswell

**Comment by NicoleNitschke** [comment]
I will fix this during the current Neos Sprint. :)

**Comment by NicoleNitschke** [comment]
## Solution
Unfortunately, the according repo https://github.com/neos/media-browser is readonly, therefore I will post the solution here for a later PR execution, until I know, how to solve the problem in code:
1.  Go to neos/Packages/Application/Neos.Media.Browser/packages/neos-media-browser/src/Variants/react_crop.vanilla-css
2. In this file do the following additions:
```css
.ReactCrop__image {
  max-height: calc(100vh - 300px);
}

.neos-media-browser .neos-modal-body {
  text-align: center;
}
```

## Result
The result will be, that the image is never higher than the viewport and the 'save' button is always visible.

### Before
![grafik](https://github.com/neos/neos-ui/assets/11499598/5c69b4ad-6c4e-41ed-b01f-0a0de4b331d9)


### After
![grafik](https://github.com/neos/neos-ui/assets/11499598/8ab08aea-95c2-4ef0-9529-05cfc4d996ba)
