### ISSUE TITLE
BUG: Node cannot be deleted in workspace if it has been removed in another dimension in the same workspace

### ISSUE THREAD

**Issue by beromir** [neos/neos-development-collection#5031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you delete a node in a workspace that has already been deleted in the workspace in another dimension, the node is not marked as removed in the database.

### Expected Behavior

There should be two database entries for the two dimensions where the node is marked as removed.

### Steps To Reproduce

1. Configure a bilingual site
```yaml
Neos:
  ContentRepository:
    contentDimensions:
      language:
        label: 'Language'
        icon: 'icon-language'
        default: de
        defaultPreset: de
        presets:
          de:
            label: 'German'
            values:
              - de
            uriSegment: ''
          en:
            label: 'English'
            values:
              - en
              - de
            uriSegment: ''

```
2. Create content node in one dimension
3. Make changes to the node in another dimension
4. Publish changes
5. Create a new workspace
6. Delete node in one dimension in the new workspace
7. Publish changes
8. Delete node in the other dimension in the workspace
9. Changes cannot be published because there are no

### Environment

```markdown
- Flow: 8.3.8
- Neos: 8.3.12
- PHP: 8.2
```

### Anything else?

If you delete the node in the two dimensions without publishing in between, two entries will be created in the database for the personal workspace. After publishing, the two nodes are marked as removed in the database for the workspace. So as it should be.
