### ISSUE TITLE
BUG: Cannot unset `defaultValue` via `CreateNodeAggregateWithNode::$initialPropertyValues`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#5154]
While the change https://github.com/neos/neos-development-collection/pull/4322 improved the unset handling of properties a lot, it introduced a regression.

Using the following NodeType

```yaml
'Flowpack.NodeTemplates:Content.Properties':
  properties:
    unsetValueWithDefault:
      defaultValue: true
      type: boolean
```

and creating it but using 

```php
PropertyValuesToWrite::fromArray(["unsetValueWithDefault" => null])
```

would originally set `unsetValueWithDefault` to `NULL` in the database. This was the behaviour in Neos 8.3 and Neos 9 before the mentioned change. Now when fetching the nodes properties we get the following result - the default value is still present:

```diff
-        "unsetValueWithDefault": null
+        "unsetValueWithDefault": true
```

The reason for that is that we filter out the unsets when creating a node (under the impression that no one would do this ^^):

https://github.com/neos/neos-development-collection/blob/7db53b6c4ec590973e063077a8c4a2ab72801c5c/Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php#L88

A workaround for now is to followup with a `SetNodeProperties` command
