### ISSUE TITLE
FEATURE: Node-Migrations across NodeBased and NodeAggregateBased filters/transformations

### ISSUE THREAD

**Issue by c4ll-m3-j4ck** [neos/neos-development-collection#5190]
### Is there an existing issue for this topic?

- [X] I have searched the existing issues

### Description

Currently, it is not possible to create a node-migration which selects by a given NodeType **and** a given PropertyValue. If I try to execute a migration with such an configuration, an error is thrown `NodeAggregate Based transformations are only supported without any node based filters`. As previously discussed with @dlubitz on slack, I get the difference between a Node and a NodeAggregate, but for integrators, the concept of Aggregates might not make sense and this seems like a rather trivial type of migration to write if you try to clean up NodeTypes in your neos-instance.

I would really like to be able to create migrations that split a given NodeType implementation into multiple discrete NodeTypes to ease our editors experience.

I have added an example of such a migration-config below:
```
comments: 'Migrate Variants to flexible/sized'
migration:
  - filters:
      - type: 'NodeType'
        settings:
          nodeType: 'Variant'
      - type: 'PropertyValue'
        settings:
          propertyName: 'areaConfigurable'
          serializedValue: true
    transformations:
      - type: 'ChangeNodeType'
        settings:
          newType: 'Variant.Flexible'
  - filters:
      - type: 'NodeType'
        settings:
          nodeType: 'Variant'
      - type: 'PropertyValue'
        settings:
          propertyName: 'areaConfigurable'
          serializedValue: false
    transformations:
      - type: 'ChangeNodeType'
        settings:
          newType: 'Variant.Fixed'
 ```
