### ISSUE TITLE
FEATURE: Allow NodeAggregate based transformations on AggregateProperties and Properties with same value

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#5213]
To be able to restructure NodeTypes, we want to enable integrators to write node migrations based on **property filter** with **NodeAggregate based transformations**.

E.g:
```
comments: 'Migrate NodeType based on property value'
migration:
  - filters:
      - type: 'NodeType'
        settings:
          nodeType: 'Some.Old:NodeType'
      - type: 'PropertyValue'
        settings:
          propertyName: 'someProperty'
          serializedValue: true
    transformations:
      - type: 'ChangeNodeType'
        settings:
          newType: 'Some.New:NodeType'
```
**Current behavior**
At the moment this throws an error `NodeAggregate Based transformations are only supported without any node based filters`.

**Targeted behavior**
We want to implement an exception from this rule, which would allow to migrate NodeAggregates also on property based filters in following cases:
* The property in the filter is a AggregateProperty -> we know the value is the same for all nodes
* All properties are equal in all dimensions -> we can safely change the NodeType as all nodes have the same value in the filtered propery.

Releated to: #5190

_Note: This was discussed in the developer weekly on 16.08.2024_
