### ISSUE TITLE
`CreateNodePrivilege` behaves differently for core and Neos Ui

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#5366]
If i have the configuration

```yaml
privilegeTargets:
  'Neos\ContentRepository\Security\Authorization\Privilege\Node\CreateNodePrivilege':
    'Vendor:CreateSimpleContent':
      matcher: 'createdNodeIsOfType(["Vendor:Content.Simple"])'

roles:
  'Neos.Neos:AbstractEditor':
    privileges:
      # Everyone can create simple content
      - privilegeTarget: 'Vendor:CreateSimpleContent'
        permission: GRANT
```

I expect that all editors to not be able to create any other, not inheriting node type, say `Vendor:Content.Other`

```
Evaluated following 1 privilege target(s):
"Vendor:CreateSimpleContent": ABSTAIN
(0 granted, 0 denied, 1 abstained)

Authenticated roles: Neos.Flow:Everybody, Neos.Flow:AuthenticatedUser, Neos.Neos:AbstractEditor ...
```

So this works for the core (i have a functional test for this)

Interestingly the Neos Ui does not detect this correctly, offering ALL node types for creation.
That can only result in that we use in here the `CreateNodePrivilegeSubject`:

https://github.com/neos/neos-ui/blob/f2d05e64afbb38e81de539f8a797f5f453d37fcb/Classes/Service/NodePolicyService.php#L120-L125

When gathering all the not allowed node types we dont find anything to exclude because the `PrivilegeManager::isGranted` will always just return true with the reason:

> No privilege of type "Neos\ContentRepository\Security\Authorization\Privilege\Node\CreateNodePrivilege" matched.

--------

Even though i started to try to deep really deep into the whole concept of how the method privileges are evaluated i could not really find out why this works differently.

In my tests i figured that i might need another privilege - that forbids to create any node:

```
    'Vendor:CreateContent':
      matcher: 'createdNodeIsOfType(["Neos.Neos:Node"])'
```

And then the Neos UI correctly filters out the not allowed node types. Im just confused why this is not needed by the core.

possibly related: https://github.com/neos/neos-development-collection/issues/1978
