### ISSUE TITLE
Bug: NodeTypes.Scdd.Website:Mixins.Card.properties.title -> None of the given schemas null,dictionary matched array

### ISSUE THREAD

**Issue by Bolkun** [neos/neos-development-collection#5520]
In Neos Project ./Packages/Sites/Scdd.Website/NodeTypes/Mixins/Card.yaml I defined 

```
properties:
    title:
      ui:
        label: i18n
        reloadIfChanged: true
        inspector:
          hidden: false
...
```

But in neos Backend i get Warning: **NodeTypes.Scdd.Website:Mixins.Card.properties.title -> None of the given schemas null,dictionary matched array**

If I comment code, the warning is gone. How to explain this behaviour and how to fix this behaviour?
`# hidden: false`

PS.: Better message explanation whould be helpdful. Thanks!

**Comment by Sebobo** [comment]
Hi, can you show the whole file?
I think the error might be in another place.

**Comment by Bolkun** [comment]
Here @Sebobo is the whole file

```
'Scdd.Website:Mixins.Card':
  abstract: true
  superTypes:
    'Neos.Neos:Content': true
    'Neos.NodeTypes.BaseMixins:ImageMixin': true
  ui:
    label: i18n
    icon: square
    position: 40
    group: teasers
  properties:
    title:
      ui:
        label: i18n
        reloadIfChanged: true
        inspector:
          # hidden: false
        inline:
          editorOptions:
            placeholder: 'Scdd.Website:NodeTypes.Mixins.Card:properties.title'
      options:
        preset: 'scddwebsite.text.inlineEditable'
    link:
      type: string
      ui:
        label: i18n
        reloadIfChanged: true
        inspector:
          editor: 'Neos.Neos/Inspector/Editors/LinkEditor'
          group: image
    text:
      ui:
        label: i18n
        reloadIfChanged: true
        inspector:
          group: image
          position: 150
        inline:
          editorOptions:
            autoparagraph: false
            placeholder: 'Scdd.Website:NodeTypes.Mixins.Card:properties.text'
      options:
        preset: 'scddwebsite.text.inlineEditable'
    tags:
      type: string
      ui:
        label: i18n
        reloadIfChanged: true
        inspector:
          group: image
          position: 160

```
