### ISSUE TITLE
BUG: Node created in dimension A is not deleted in dimension B with fallback to dimension A

### ISSUE THREAD

**Issue by crydotsnake** [neos/neos-development-collection#5545]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Given i have the following content dimension configuration with a fallback:

```yaml
Neos:
  ContentRepository:
    contentDimensions:
      language:
        label: 'Language'
        icon: icon-language
        default: 'de_de'
        defaultPreset: 'de_de'
        presets:
          de:
            label: 'Deutsch'
            values:
              - de
            uriSegment: de
          de_de:
            label: 'Deutsch (Deutschland)'
            values:
              - de_de
              - de
            uriSegment: de-de
          de_ch:
            label: 'Deutsch (Schweiz)'
            values:
              - de_ch
              - de
            uriSegment: de-ch
```

- create a node in the de dimension
- switch to the de_ch dimension and delete the node you have created in the de dimension

The node is still visible in the de dimension (also visible in the frontend). And if you then switch back to the de_ch dimension (or reload) the node you have deleted before is visible again.

### Expected Behavior

The node should be deleted in the respective dimensions.

### Steps To Reproduce
- Created a `Settings.ContentRepository.yaml` file with the content above.
- Create a node in the DE dimension
- switch to the de_ch dimension and delete the node you have created.
- Switch back to the DE dimension
- You should see the node is still visible in backend/frontend.

### Environment

```markdown
- Flow: 8.3.17
- Neos: 8.3.17
- PHP: 8.2
```
