### ISSUE TITLE
Graphicsmagick / Neos problem when selecting an image for a node property

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#826]
Jira issue originally created by user kapale:

It seems there is a problem with graphicsmagick and neos. 
I’m not sure if this is a bug in graphicsmagick or in neos. 
My fresh installation of GraphicsMagick 1.3.21, PHP 5.6.10 as FPM, nginx/1.8.0 on Mac OS 10.10.3 (using homebrew) led my directly in a strange problem: 

I could add image node elements to the page, select them, crop them and so on without any problem. But if I tried to add the image on a column node element as a background image (I added a property for that) I couldn’t save it. Preview image and so on was shown, but I got a 502 Bad Gateway error back as soon as I clicked „Apply". I found out that the php fpm worker crashed as soon as I tried to save the image.
Because this was a crash of php-fpm worker, no php error.log with more details was written.

My node configuration:

``` yaml
'TYPO3.Neos.NodeTypes:Column':
  superTypes:
    'TYPO3.Neos:Content': TRUE
  abstract: TRUE
  ui:
    group: 'structure'
    label: 'Column'
    icon: 'icon-columns'
    inlineEditable: TRUE
    inspector:
      groups:
        row:
          label: 'Bootstrap Grid Container/Row'
          position: 10
        menu:
          label: 'Add Section to Menu'
        sectionBackground:
          label: 'Background Image For Section'
          position: 20
  properties:
    layout:
      type: string
      ui:
        label: 'Column Layout'
        inspector:
          group: 'row'
          editor: 'TYPO3.Neos/Inspector/Editors/SelectBoxEditor'
    backgroundClass:
      type: string
      defaultValue: 'background-default'
      ui:
        label: 'CSS background class for row'
        reloadIfChanged: TRUE
        inspector:
          group: 'row'
          editor: 'TYPO3.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            values:
              'background-default':
                label: 'Default Background'
              'background-grey':
                label: 'Grey Background'
              'background-image':
                label: 'Image Background'
    showInMenu:
      type: boolean
      defaultValue: FALSE
      ui:
        label: 'Show in Menu'
        reloadIfChanged: FALSE
        inspector:
          group: 'menu'
    navigationTitle:
      type: string
      ui:
        reloadIfChanged: FALSE
        label: 'Navigation Title'
        inspector:
          group: 'menu'
    navigationId:
      type: string
      ui:
        reloadIfChanged: FALSE
        label: 'Jump Mark ID'
        inspector:
          group: 'menu'
    backgroundImage:
      type: TYPO3\Media\Domain\Model\ImageInterface
      ui:
        label: 'Background Image'
        inspector:
          group: 'sectionBackground'
          editorOptions:
            features:
              crop: TRUE
    parallaxSpeed:
      type: integer
      defaultValue: 300
      ui:
        reloadIfChanged: FALSE
        label: 'Parallax Background Scroll Speed'
        inspector:
          group: 'sectionBackground'
```

 Jira-URL: https://jira.neos.io/browse/NEOS-1357
