### ISSUE TITLE
Wrong load order for Module resources (additionalResources)

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#858]
Jira issue originally created by user mabolek:

When creating a backend module for Neos and assigning additional resources in Settings.yaml, these resources are loaded first, instead of last. This is especially true when importing additional CSS, because TYPO3.Neos/Styles/Includes-built.css will override any CSS without an !important.

**A basic example:**

My module fooModule has a CSS file called fooModule.css:

```
.neos div {
    padding: 10px;
}
```

This is included in Settings.yaml like this:

```
TYPO3:
  Neos:
    modules:
      administration:
        submodules: 
          fooModule:
            label: 'Foo Module'
            controller: '\Foo\Bar\Controller\FooController'
            additionalResources:
              styleSheets:
                - resource://Foo.Module/Public/StyleSheets/fooModule.css
```

At testsite.local/neos/administration/fooModule, fooModule.css will be included before other CSS files and the element style ".neos div" will be overriden by ".neos div" in TYPO3.Neos/Styles/Includes-built.css.
- Mathias
  
  Jira-URL: https://jira.neos.io/browse/NEOS-1491
