### ISSUE TITLE
Can't switch language in backend on start page only

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#862]
Jira issue originally created by user kapale:

I have a multi language webpage with four languages (de,en,ru,fr).
The defaultUriSuffix in Routes.yaml is set to: 
`defaultUriSuffix: ''`
(See Settings.yaml below.)

I can change the language in the backends language selector on every page, except the start page. It seems that a missing {color:red}**/**{color} causes the problem.

This link is working if I added to the browsers url: 
http://my-website.de/ru/@user-myuser;language=ru,en,de

This link isn't working and shows a 404 Neos Page not found error:
http://my-website.de/ru@user-myuser;language=ru,en,de
(there is no **{color:red}/{color}\* before the *@user...**)

My Routes.yaml:

``` yaml
##
# TYPO3 Neos subroutes

-
  name: 'TYPO3Neos'
  uriPattern: '<TYPO3NeosSubroutes>'
  subRoutes:
    'TYPO3NeosSubroutes':
      package: 'TYPO3.Neos'
      variables:
        'defaultUriSuffix': ''
```

My language Settings.yaml:

``` yaml
TYPO3:
  TYPO3CR:
    contentDimensions:
      'language':
        label: 'Language'
        icon: 'icon-language'
        default: 'de'
        defaultPreset: 'de'
        presets:
          'de':
            label: 'Deutsch'
            values: ['de']
            uriSegment: 'de'
          'en':
            label: 'English'
            values: ['en','de']
            uriSegment: 'en'
          'ru':
            label: 'русский'
            values: ['ru','en','de']
            uriSegment: 'ru'
          'fr':
            label: 'français'
            values: ['fr','en','de']
            uriSegment: 'fr'
```

 Jira-URL: https://jira.neos.io/browse/NEOS-1523
