### ISSUE TITLE
Custom server-side validation for node properties

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#968]
Configuring validators for a node type property has no effect besides validating the input in the user-interface. The validation rules should be enforced both on the server-side and the client-side to prevent inconsistent data.

We need an extensible but easy way to configure both the client-side and server-side validation logic to use for a given validation type.

*Update from 2019-12-04:*
With https://github.com/neos/neos-ui/pull/2351 The default validators (`Neos.Neos:...`) are applied on the server-side, too. But that is currently not configurable and does not work for custom validators.

Related: #2349, #2348

**Comment by bwaidelich** [comment]
## Some ideas

Given we have:

```yaml
'Some.Package:SomeNodeType:
  #...
  properties:
    'someProperty':
      #...
      validation:
        'Neos.Neos/Validation/NotEmptyValidator': []
        'Neos.Neos/Validation/StringLengthValidator':
          maximum: 255
```
Let's assume we additionally want to validate this property against some data that is only available on the server-side (e.g. check against some web service, validate asset source, ...).

Some options I could imagine:

#### Additional config key:

```yaml
'Some.Package:SomeNodeType:
  #...
  properties:
    'someProperty':
      #...
      validation:
        # ...
      server-side-validation:
        'Some\Custom\Validator\Class\Name`: ['some', 'options']
```

for B/C the `validation` rules would still apply to both, UI & server-side, for the default validators.

#### Using presets

```yaml
'Some.Package:SomeNodeType:
  #...
  properties:
    'someProperty':
      #...
      validation:
        'someValidationPreset': true
```
and in some `Settings.yaml` s.th. along the lines of

```yaml
validationPresets:
  #...
  properties:
    'someValidationPreset':
      ui:
        'Neos.Neos/Validation/NotEmptyValidator'
        'Neos.Neos/Validation/StringLengthValidator':
          maximum: 255
      server:
        'Neos\Flow\Validation\Validator\NotEmptyValidator'
        'Neos\Flow\Validation\Validator\StringLengthValidator':
          maximum: 255
        'Some\Custom\Validator\Class\Name`: ['some', 'options']
```
for B/C we could still support the existing syntax
